### ISSUE TITLE
"Only variables should be passed by reference in /srv/www/viewfind.com/current/web/app/mu-plugins/controller/src/Loader.php 

### ISSUE THREAD

**Issue by aaroneight** [soberwp/controller#1]
I'm currently getting this error.   Any idea why?

**Comment by darrenjacoby** [comment]
Hi @aaroneight, can you please show me the code you're using for your controller (class) and template so that I have better insight and can try recreate?

**Comment by aaroneight** [comment]
I figured it out...  My path defining a new controller path location in my functions.php was wrong.
