### ISSUE TITLE
archive templates

### ISSUE THREAD

**Issue by jajouka79** [soberwp/controller#10]
i am trying to make the blade vie tpl files as easy to use as possible for designers. I really like the way that the controller allows us to use a variable to call a function, and trait work really well for partials. however i could do with a bit of guidance on how to use the archive comtrollers/views, like archive.php or even archive-news_article.php or even index.php.i

so far i have this -

_src/controllers/archive.php_

    public function posts(){
        global $posts;
        $posts2 = null;
        $x = 0;
        foreach ($posts as $p){
            $post_excerpt = substr(strip_tags($p->post_content, '<b><div><p><i>'), 0, 250);
            $post_excerpt .= '<a href="' . get_permalink($p) . '">' . '...read more</a>';
            $p->post_excerpt = $post_excerpt;
            $posts2[$x] = (array) $p;
            $x++;
        }
        return (array) $posts2;
    }

_archive.blade.php_

@foreach($posts as $post)
@include ('partials.content-'.($post->post_type !== 'post' ? $post->post_type : get_post_format()), $post)
@endforeach

i am passing the $post value to the include partial statement

in _content-program.blade.php_ to get the custom excerpt, i have to use

{!! $post['post_excerpt'] !!}

i would like to use 

{!! $post_excerpt !!}

how can i do this with a function post_excerpt to the variable returns each post excerpt in a loop for the partial template?  

thanks

**Comment by slackday** [comment]
Disclaimer: I do not use this controller yet but I've been following it and will try it on my next project.

However I started using Sage with Blade recently and I took a similar approach as this plugin. I'll try explain how I did it by modifying your code. Maybe it can help you. And I will follow this thread for the "real" answer and hopefully learn about this plugin :)

In my opinion you shouldn't render any HTML in the controller.

`src/controllers/the-post.php`

```
add_action('the_post', function ($post_object) {
  if (!is_admin())
  {
    if (in_array(true, array(
      is_archive(),
    )))
    {
      $ID = $post_object->ID;
      $post_type = $post_object->post_type;

      $postData = setup_post_data($ID);

      sage('blade')->share('postData', $postData);
    }
  }
});
```

`src/data/post-data.php`

```
function setup_post_data($ID = 0)
{
  if (!$ID) return false;

  $postData = array();

  $post_type = get_post_type($ID);
  $postData['ID'] = $ID;
  $postData['post_excerpt'] = substr(strip_tags(get_post_field('the_content', $ID), '<b><div><p><i>'), 0, 250);
  $postData['permalink'] = get_permalink($ID);

  ...
  whatever more you need. Post type specific stuff.. custom fields... etc.
  ...

  return $postData;
}
```

Rendering

`templates/archive.blade.php`

```
@extends('layouts.base')

@section('content')
  @while (have_posts())
          @php(the_post())
          @include ('partials/archive-post')
  @endwhile
@endsection
```

extract in PHP takes every key in array and makes available as variable. I use this to set `href` to value of permalink. I didn't understand how you want to display the excerpt but `$post_excerpt` is available aswell since it's key of $postData array.

`templates/partials/archive-post.blade.php`

```
@if (isset($postData) && $postData)
  @php(extract($postData))
  <a href="{{ $permalink }}">
     ...read more
  </a>
@endif
```

Sorry if this is off-topic to this plugin but I'm very excited after using blade templates with Sage and WordPress and is eager to learn more and try this plugin :)

Good luck!

**Comment by darrenjacoby** [comment]
@jajouka79 there are a few ways to accomplish this, I'm going to set up your use case locally and then will respond in full once I've tested.

**Comment by darrenjacoby** [comment]
If, all you are trying to do, is modify the excerpt, I would recommend you rather use a filter for the function https://codex.wordpress.org/Plugin_API/Filter_Reference/get_the_excerpt as per normal.

You could then just use archive.blade.php like this, for each post.

```
@while (have_posts()) @php(the_post())
    @php(the_excerpt())
@endwhile
```

No need for a controller method then.

If you would like to stick with your approach, by modifying the $post objects, you could use the following, returning the post data as an object (like WordPress does by default)

**sec/controllers/Archive.php**

```
public function posts()
{
    global $posts;
    foreach ($posts as $post) {
        $post->excerpt = substr(strip_tags($post->post_content, '<b><div><p><i>'), 0, 250) . '<a href="' . get_permalink($post) . '">' . '...read more</a>';
        $results[] = (object) $post;
    }
    return $results;
}
```

**templates/archive.blade.php**

@foreach($posts as $post)
    {!! $post->excerpt !!}
  @endforeach

**Comment by darrenjacoby** [comment]
Hey @jajouka79 @slackday 

So I've updated Controller to 1.0.2 which I think addresses this use case much better.  

You can now use `public static function` and reference from within the Blade template.

**src/controllers/Archive.php**

```php
<?php

namespace App;

use Sober\Controller\Controller;

class Archive extends Controller
{
    public static function excerpt()
    {
       // you can handle computations within the function and return a value
        return get_post()->post_excerpt;
    }
}
```

**templates/archive.php**

```php
@extends('layouts.base')

@section('content')
  @while (have_posts()) @php(the_post())
    {{ \App\Archive::excerpt() }}
  @endwhile
@endsection
```

**Comment by slackday** [comment]
Cool this is very clean! Good job

**Comment by jajouka79** [comment]
im not sure i explained myself clearly, i want a single word command for designers to use. excerpt was a bad example to use, it could be $authors_age. i already have $post['authors_age'] working. in the content partial, i wanted $authors_age to work

**Comment by darrenjacoby** [comment]
@jajouka79 the method name becomes the variable name.  You would need to then have a separate method for $authors_age.  I would recommend making the array an object and then simply using $post->authors_age

**Comment by jajouka79** [comment]
ive done this, i know that i need method authors_age(), I have tried this in the archive.php in a trait, i have tried passing variables to it, and I have tried passing the post data through from archive.blade.php in the include to content.blade.php, I can't get it to work

**Comment by darrenjacoby** [comment]
@jajouka79 I'll need to see the actual code to replicate.  Is it on GitHub?

**Comment by jajouka79** [comment]
there's no code to show other than whats in my original post. i have tried lots of code but nothing that works. in single and page templates designers can easily use a variable that calls the corresponding method e.g. $coach_age. but when they get to the list templates like archive.php or archive-coach.php they have to use $post->coach_age. if you have 10 designers all at different levels of ability it would be a lot easier and more consistent if they didn't have to do this. they would work only on the partials only so the content-blade.php partial (which shows the teaser on lost templates), I would like them to be able to use $coach_age.

**Comment by darrenjacoby** [comment]
@jajouka79, easiest is to go with @slackday recommendation. 

Controller;
```php
public function posts()
{
    global $posts;
    foreach ($posts as $post) {
        $post->post_excerpt = substr(strip_tags($post->post_content, '<b><div><p><i>'), 0, 250) . '<a href="' . get_permalink($post) . '">' . '...read more</a>';
        $results[] = (array) $post;
    }
    return $results;
}
```
Template;
```php
@foreach($posts as $post)
    @php(extract($post))
    {!! $post_excerpt !!}
  @endforeach
```

**Comment by darrenjacoby** [comment]
You could also use $post->coach_age in single.php by modifying the $post object in the Single controller.  

I think your use case may be out of scope for this plugin, as in a way, this relates more to the way WordPress handles loops. 

If you're only giving designers access to the partials, the above method does work. 

```php
@foreach($posts as $post)
    @php(extract($post))
    @include ('partials.content-'.(get_post_type() !== 'post' ? get_post_type() : get_post_format()))
  @endforeach
```

You could now access $post_excerpt within the partial.

**Comment by jajouka79** [comment]
@forelse($posts as $post)
            @php(extract($post))
            @php (extract($post['post_meta']))
            @include ('partials.content-'.(get_post_type() !== 'post' ? get_post_type() : get_post_format()))

        @empty
            <div class="alert alert-warning">
                {{ __('Sorry, no results were found.', 'sage') }}
            </div>
        @endforelse


this makes the variables available in the partial, thanks

**Comment by jajouka79** [comment]
i have a lot of traits that work great for single / page templates, for eg, featured images, post classes, post meta. however i can't get them to work with archive templates. is there a way to pass a post id to the traits so i can use them with lists?

**Comment by darrenjacoby** [comment]
@jajouka79 you could use static functions within the trait.  I think that will be the only way to pass on the post id.
