### ISSUE TITLE
ACF module with a term controller

### ISSUE THREAD

**Issue by thomascharbit** [soberwp/controller#101]
Using `$acf = true` on a term controller (for taxonomy term template like _taxonomy-$taxonomy.blade.php_) is returning the wrong fields for me.

It returns the loop first post fields instead of the actual term fields.
It works correctly if there is no posts in the loop (term with no linked posts).

I guess the issue comes from the use of ACF's `get_fields()` function, which needs more context to understand we are looking at a term and not a post type?

It looks like passing `get_queried_object()` as a second parameter fixes it, unsure if this is safe to do!

**Comment by thomascharbit** [comment]
thanks @darrenjacoby!

**Comment by darrenjacoby** [comment]
I see no problem using `get_queried_object()` for ACF fields, so I've gone with that approach. 

All results seem like what we want in this case, https://codex.wordpress.org/Function_Reference/get_queried_object

Included in next release.

**Comment by thomascharbit** [comment]
Awesome, thanks again
