### ISSUE TITLE
Acf Module Warning when no ACF fields on page

### ISSUE THREAD

**Issue by lhilton** [soberwp/controller#102]
On some pages a warning will be shown when a given page has not ACF fields. The message is:

`Warning: array_merge(): Argument #2 is not an array in /sites/testsite.test/www/wp-content/themes/testtheme/vendor/soberwp/controller/src/Controller.php on line 151`

The issue is that in `Module/Acf.php` it is possible for the `setData()` function to set `$this->data` to a boolean false, I am guessing this is done one line 77 specifically. Because of my stack I cannot simply disable this on a per-template basis. After reviewing the code, it appears that `$this->data` should always be an array anyways.

**Comment by darrenjacoby** [comment]
I have noticed this and also wrote a fix, I'll compare with your PR to resolve this weekend.

**Comment by adviva** [comment]
Hi there! Any update?

**Comment by darrenjacoby** [comment]
@adviva this weekend, sorry. Last weekend was my birthday so it got away from me.

**Comment by adviva** [comment]
@darrenjacoby thank you for replying me and happy b day 😄 🎉

**Comment by pfalomo** [comment]
thank you @darrenjacoby
