### ISSUE TITLE
Using constructor to pull data?

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#11]
My intent was to use a simple constructor on my controller to pull in all the ACF field data for the page and store in a protected $fields property which could be accessed by the controller methods.

Unfortunately, this does not seem to be working. I'm not sure why, but I also created the below non ACF test which also does not work.

```

<?php

namespace App;

use Sober\Controller\Controller;

class FrontPage extends Controller {
    
    protected $message;

    public function __construct() {
        parent::__construct();
        $this->message = "This is my message.";
    }

    /**
     * Return message
     *
     * @return string
     */
    public function message(){
        return $this->message;
    }

}

```

Any ideas?

**Comment by darrenjacoby** [comment]
That's one caveat.  The __construct is reserved for the parent.  But, by default, Controller does execute all functions within the class.  So you could simply use a protected or private function and it should work. 

```php
protected function message {
    $this->message = "This is my message.";
}
```

**Comment by christianmagill** [comment]
Alright, I'll use "init" just for the sake of consistency. This should probably be mentioned in the documentation somewhere.

**Comment by darrenjacoby** [comment]
@christianmagill true, I might re-write the Controller __construct to use a more arbitrary method name—so expect this to change in the next release.

**Comment by darrenjacoby** [comment]
@christianmagill did you get this working?  

I'm working on a project now and it seems that I have encountered the same issue which could be a pretty large oversight on my behalf.

**Comment by christianmagill** [comment]
I haven't, got pulled into another project so will be revisiting the issue later.

I was also wondering whether there would be any issues with directly adding to the data array via such a constructor method. Like if you wanted to pull all ACF fields and make them accessible with an enclosing array.

**Comment by darrenjacoby** [comment]
OK, I'm going to fix this tomorrow.  It's a large oversight.  Controller should run all protected and private functions, in their current order, automatically. 

If I understand correctly, I think that's exactly what I'm trying to do at the moment actually. 

```php
class TemplateMenu extends Controller
{
    use Hero;

    public $data = [];

    protected function repeater()
    {
        if (have_rows('menus')) {
            while (have_rows('menus')) {
                the_row();
                $this->data['names'][] = get_sub_field('name');
                $this->data['menus'][] = get_sub_field('menu');
            }
        }
    }

    public function names()
    {
        return $this->data['names'];
    }

    public function menus()
    {
        return $this->data['menus'];
    }
}
```

**Comment by christianmagill** [comment]
Do you think it's appropriate to run all methods automatically?

Some of the methods might simply be the result of refactoring, and not meant to work out of context.

I'd suggest to make behavior more predictable either:

- Allow use of __constuct() with documentation that the first line must call parent::__construct()
- Provide a pseudo constructor, for example: init() which could be used to bootstrap any other methods desired.

As far as ACF data I am thinking something similar to:

```
public function __construct(){
   parent::__construct();
   $fields = get_fields();
   $this->data = array_merge($fields, $this->data);
}

```

**Comment by darrenjacoby** [comment]
I started working on this now and I agree.  

I think a pseudo constructor might be the cleanest (__init for example), although it would be ideal to use __construct for consistency.  I just wish there was a way to not have to use parent::__construct().

**Comment by christianmagill** [comment]
Yeah, I see what you're saying. Either way though there is some learning to be done. I kind of prefer the __construct method with parent::__construct() as it is less magical.

Knowing that the class extends Controller, you expect their to be a parent constructor. You wouldn't expect an __init method without learning it from the documentation. When I first was first trying to implement, my first thought was to use __construct / parent::__construct, but I think I had the order wrong as the parent's constructor needs to set things up first.

**Comment by darrenjacoby** [comment]
Cool, thanks for the feedback.  I will find the best solve tomorrow, but I agree with your line of thinking.

**Comment by darrenjacoby** [comment]
@christianmagill I've implemented this in dev-master and 9.0.0-beta2.  You can now use __construct in the child Class.  No need to use parent::__construct() either.

**Comment by christianmagill** [comment]
Thanks for this! How are overwrites handled across the constructed data and the method names? Also how is it handled across the template hierarchy.

Thanks

**Comment by christianmagill** [comment]
Also, is there a way to add to the Controller data that will be sent to view.

Currently, $this->data is protected.

public function __construct(){
   $fields = get_fields();
   $this->data = array_merge($fields, $this->data);
}

Maybe a private __mergeData() method would useful.
