### ISSUE TITLE
ACF fields not coming through for custom fields on archives

### ISSUE THREAD

**Issue by synio-wesley** [soberwp/controller#115]
It looks like setting `protected $acf = true;` and then using `$acf_variable` returns an empty string for other languages with WPML... But `get_field('acf_variable')` does work.. Is this a bug? or missing functionality?

**Comment by darrenjacoby** [comment]
I'm wondering if this may be an issue with ACF or WPML itself. The ACF module in Controller is pretty simple, using the ACF function `get_fields` to get all the fields. 

```php
$query = get_queried_object();

$this->data = get_fields($query);
```

**Comment by synio-wesley** [comment]
@darrenjacoby I found out that this is related to the problem. Because the get_queried_object() returns the custom fields of one of the products in the `ArchiveProduct` controller, probably because of how the loop works. I worked around this for now by overriding the `__after()` function and then setting `$this->data` to `array_merge($this->data, $acfData)` where `$acfData` contains data I retrieved from ACF myself using a more advanced query in case we are on a shop archive page...

It would be great if SoberWP would support this in the expected way automatically though.

**Comment by synio-wesley** [comment]
Sorry, upon further inspection it does look like I'm mixing up two separate problems I have had with SoberWP here... feel free to close the ticket, because I'm mixing things up now.

I can open up 2 new tickets where I explain the 2 (different) problems I have had separately (and my workaround for them). That would probably be better?

**Comment by slackday** [comment]
Are you using the WPML ACF plugin? https://wpml.org/documentation/related-projects/translate-sites-built-with-acf/

I'm curious because I have never ran into this issue myself.
