### ISSUE TITLE
Undefined variable $last when debugging with only one class

### ISSUE THREAD

**Issue by dotsam** [soberwp/controller#116]
Commit 0e92b7d looks to have been intended to fix a bug where `@debug` would print the `App` class twice, but appears to have had the unintended side effect of throwing errors when only one class is loading for a request.

Submitting a PR in a moment with a fix that moves all of the checking for first/last classes inside the count > 1 conditional. This should skip checking for first/last if there's only one class, while keeping the original fix.

**Comment by darrenjacoby** [comment]
Thanks for the PR, merged in dev-master and will tag soon.
