### ISSUE TITLE
base.blade.php renaming to app.blade.php

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#12]
This will probably effect things when the change gets merged.

https://github.com/roots/sage/pull/1864/commits

**Comment by darrenjacoby** [comment]
@christianmagill thanks for the heads up.  I will track this and update when it's merged.

**Comment by darrenjacoby** [comment]
@christianmagill this was merged into Sage 9 dev-master a few hours ago.  I have aligned the versioning of Controller to the same as that of Sage.  So you can use `composer require soberwp/controller:dev-master` to use with Sage dev-master.
