### ISSUE TITLE
ACF vars with dash

### ISSUE THREAD

**Issue by tillkruss** [soberwp/controller#122]
I'm working with ACF variables named with dashes: `program-notify-form`.

Is there any chance we can support them directly in templates as `$program_notify_form`?

**Comment by darrenjacoby** [comment]
I'm assuming you are you using the acf module to automate the fields?

**Comment by tillkruss** [comment]
Yes, I'm just setting `$acf = true` to get all fields.

**Comment by bckcmo** [comment]
@darrenjacoby I have a proposed fix for this. I'm not sure if you welcome contributions, but I am going to go ahead and submit a pull request for you to review. Thanks!
