### ISSUE TITLE
Question: How to modify the loop?

### ISSUE THREAD

**Issue by eduardoarandah** [soberwp/controller#128]
What would be the best approach to modify **the loop with filters in an archive page**?

Let's say I have a "boats" archive like this:

![imagen](https://user-images.githubusercontent.com/4065733/59276970-eaf2c200-8c24-11e9-9ec5-3e9fbaf15f72.png)

I'm solving it by modifying global $wp_query inside a function called wp_query() which gets called along the way.  like this:

```
namespace App\Controllers;

use Sober\Controller\Controller;

class ArchiveBoat extends Controller {

  public function wp_query() {

    $meta_query = [
      'relation' => 'and',
    ];
    // price from
    if (!empty($_GET['price-from'])) {
      $meta_query[] = [
        [
          'key'     => 'price',
          'value'   => $_GET['price-from'],
          'compare' => '>=',
        ],
      ];
    }
    // price to
    if (!empty($_GET['price-to'])) {
      $meta_query[] = [
        [
          'key'     => 'price',
          'value'   => $_GET['price-from'],
          'compare' => '<=',
        ],
      ];
    }

    $args = [
      'post_type'      => 'boat',
      'posts_per_page' => 9,
      'paged'          => get_query_var('paged') ? get_query_var('paged') : 1, // global pagination
      'meta_query'     => $meta_query,
      // order by meta
      'meta_key'       => 'price',
      'orderby'        => 'meta_value',
      'order'          => 'ASC',
    ];

    Global $wp_query;
    $wp_query = new \WP_Query($args);
    // echo $wp_query->request;
    return $wp_query;

  }
```

**I can't find another way to hook into the loop arguments.**
Is this the best approach? 
how do you do it?

Is it better to use __before() function? or __construct()?

**Comment by slackday** [comment]
I think this is best handled by modifying the query before it is executed. The `pre_get_posts` hook should have you covered. Have a look at https://wpshout.com/practical-uses-pre_get_posts/

**Comment by eduardoarandah** [comment]
@slackday yeah, I thought about that, but then I thought:

If I do a `pre_get_posts` then I'd have to apply some conditions like `is_archive && get_post_type=="boat"` and that is exactly what the controller does for us. 

What's your strategy to not get your code all scattered around? let's say you have 10 custom post types archives with filters. Where would you put your code and how?

**Comment by slackday** [comment]
You are correct you have to do your own checks to determine when to modify your query. I usually create a separate file usually called `pre-get-posts.php` and include it in functions. This way at least I have all code that modifies the query in one place. Even if the controller follows WordPress templating I think your problem is outside of the scope of what it does. I prefer to keep to only to handle data to template files.

Here is an example `pre-get-posts.php` to get you started

```
<?php

namespace App;

add_filter('pre_get_posts', function ($query) {
  if (is_admin() || !$query->is_main_query()) {
    return;
  }

  if ($query->is_post_type_archive('calendar_post') || is_tax('calendar_category')) {
    $current_date = date('Ymd');

    $query->set('posts_per_page', -1);
    $query->set('meta_key', 'date_start');
    $query->set('orderby', 'meta_value');
    $query->set('order', 'ASC');
    $query->set('meta_query', array(
      'relation' => 'OR',
      array(
        'key' => 'date_start',
        'value' => $current_date,
        'compare' => '>=',
        'type' => 'NUMERIC',
      ),
      array(
        'key' => 'date_end',
        'value' => $current_date,
        'compare' => '>=',
        'type' => 'NUMERIC',
      ),
    ));
  }

  return $query;
});
```

**Comment by eduardoarandah** [comment]
Awesome! Thanks man!
