### ISSUE TITLE
Sage 10

### ISSUE THREAD

**Issue by andrewscofield** [soberwp/controller#134]
I'm trying the beta and doesn't work out of the box... I've installed it using composer already, but not really sure how to initialize it on Sage 10.

**Comment by Log1x** [comment]
Sage 10 doesn't use this package. It uses Composers instead which are built in.

**Comment by andrewscofield** [comment]
Yes, I realized that. I'm new to Composers and getting caught up. While reading the blog on [Sage 10 and Composers ](https://roots.io/working-with-composers-in-sage-10/) it mentions you can use both together and I was wondering how that works. Sounds like that is outdated info though?

**Comment by Log1x** [comment]
Yeah, more than likely outdated. I'd urge you to avoid this package with Sage 10.

**Comment by andrewscofield** [comment]
Got it, thanks. 

Could you point me in the right direction for replacing a controllers static functions using Composers/Sage10? I guess I used to use those mainly for helper type of functions. Like formatting dates, hex2rgb, or site specific functions. Where would I put those in Sage 10 so they can be called from a blade view?

**Comment by Log1x** [comment]
If you could close this and re-ask your question on Discourse of `what is the alternative to static functions from Controller using Sage 10 with Composer` – I'd like to answer that there so it's not hidden in a random issue.

**Comment by Jamiewarb** [comment]
This link appears at the top of Google for a search on Sage 10 Controllers.

Any chance you could add a link to either of the above mentioned places for ease of navigation for other googlers? 🙏

**Comment by darrenjacoby** [comment]
@Jamiewarb Sure, will add to the readme!
