### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dotsam** [soberwp/controller#136]
Can we get a new release cut and pushed to packagist? There have been a number of helpful commits made since 2.1.1 was released almost a year ago, and it would be nice not to have to pull from dev-master in projects to get these fixes.

Thanks!

**Comment by darrenjacoby** [comment]
Yes, I will tag another version this week!

**Comment by dotsam** [comment]
Just poking on this one again

**Comment by darrenjacoby** [comment]
@dotsam Just to let you know I got version 2.1.2 tagged. Long overdue, sorry about that!
