### ISSUE TITLE
Static function Snake or Camel Case?

### ISSUE THREAD

**Issue by da-kicks-87** [soberwp/controller#143]
What it best practice when naming a static function in the controller? 
The guide mentions that with non static functions Camel case gets converted to Snake case. 
WP core functions use snake case.  Would there be a reason then for using Camel Case for function names in WP?

**Comment by darrenjacoby** [comment]
I would recommend camel case as per [PSR](https://siderlabs.com/blog/5-php-coding-standards-you-will-love-and-how-to-use-them-adf6a4855696/) guidelines, I would consider the WP coding standards questionable.

**Comment by da-kicks-87** [comment]
Thanks for your input. I typical use Camel case for functions and have them named as a verb.  The guide doesn't use a verbs for it's examples.
