### ISSUE TITLE
Upgrading Sage 9 project to Beta 3

### ISSUE THREAD

**Issue by rorymcdaniel** [soberwp/controller#15]
I described my problem here, I'm not sure if this is an issue with the plugin and Sage moving to beta 3, or if I've just done something wrong.

https://discourse.roots.io/t/upgrading-sage-9-project-to-beta-3-with-soberwp-controller/9445

**Comment by darrenjacoby** [comment]
@rorymcdaniel I'm looking into this now, and will release a new beta3 release/tag.

**Comment by darrenjacoby** [comment]
@rorymcdaniel you can grab the latest 9.0.0-beta3 release and custom templates should work again—let me know if it solves it for you.

**Comment by rorymcdaniel** [comment]
Worked perfectly, thanks!
