### ISSUE TITLE
Controller not passing data to WooCommerce template

### ISSUE THREAD

**Issue by vdrnn** [soberwp/controller#16]
I'm trying to pass data from App.php controller to the WooCommerce templates. 
The templates structure is setup as described in this post: https://discourse.roots.io/t/latest-sage-9-blade-and-woocommerce/9462

There is a woocommerce.blade.php in views and the archive-product.php and single-product.php in views/woocommerce. 

Not 100% sure if it's really a controller issue though?

**Comment by vdrnn** [comment]
Because the woocommerce templates are not blade templates. I figured out :(

**Comment by vdrnn** [comment]
Now I have the following template structure.

`/resources/views/woocommerce.blade.php` which looks like this: 

```
@extends('layouts.app')

@section('sidebar-complementary')
  @include('partials.sidebar-complementary-shop')
@endsection

@section('content')
  @php(woocommerce_content())
@endsection
```

And I have `/resources/views/woocommerce/archive-product.php` which contains

`<?php echo App\Template('woocommerce');
`

When not on the shop (https://myproject.dev/shop) I get the data that I'm calling from the `App.php` controller, specifically ACF data.

Output of `@debug('controller)` on shop:

`$post » object
`

Output of `@debug('controller)` on every other page:

```
$post » object
$acf_data » array[8]
$fetch_all_crue » object
$fetch_all_releases » object
$get_background » array[1]
```

Am I missing something here?

**Comment by darrenjacoby** [comment]
Hey @vdrnn , could you check out the body classes for the woocommerce archive product page?  I just want to see what it's passing on. 

Then, would it be possible to upload your current theme/setup to GitHub? 

I haven't tested Controller with WooCommerce so it would be good to do some testing there.

**Comment by vdrnn** [comment]
@darrenjacoby nice, thanks for the quick reply.

These are the body classes `archive post-type-archive post-type-archive-product logged-in admin-bar bg-cover woocommerce woocommerce-page app-data archive-data archive-product-data customize-support`

The project is on Github already, I will invite you to the project, so you can have a look around and test it yourself.

**Comment by darrenjacoby** [comment]
@vdrnn thanks! 

Looks like the classes are being passed correctly so that's a good start.

**Comment by MWDelaney** [comment]
Did you guys ever get anywhere on this? I'm having the same problem.

**Comment by darrenjacoby** [comment]
Hi @MWDelaney,

No solution exists at the moment unfortunately. 

I did do some testing, and it seems, even with a basic setup of passing data to the template it doesn't work (ie. not using the Controller, but just trying to pass using the basic filter)

```
add_filter('sage/template/woocommerce/data', function ($data) {
    $data = 'testing';
    return $data;
});
```
Controller relies on this filter to pass content, so I'm uncertain at the moment if the fix should come from within Controller, or from the Blade implementation of WooCommerce templates.

**Comment by MWDelaney** [comment]
Darren,
Thanks for the quick response. I've moved my necessary controller-type variable settings into my template files for now. Hopefully there will be a solution eventually! Let me know if I can be of any assistance testing solutions.

**Comment by christianmagill** [comment]
@MWDelaney I'd suggest raising the issue at the Sage repo.

**Comment by darrenjacoby** [comment]
Has anyone created this issue at the Sage repo?  Else I will raise an issue there so we can try get this fixed. 

@vdrnn @MWDelaney

**Comment by MWDelaney** [comment]
I have not. I've been too busy :) @darrenjacoby

**Comment by osadler** [comment]
@MWDelaney I've had this issue. Replace `<?php echo App\Template('woocommerce');` in archive-product.php and single-product.php with:
```
$template = 'woocommerce';
$data = collect(get_body_class())->reduce(function ($data, $class) use ($template) {
    return apply_filters("sage/template/{$class}/data", $data, $template);
}, []);
echo App\Template($template, $data);
```

**Comment by darrenjacoby** [comment]
Thanks for this @osadler 

I'll see if there's a way to include this in Controller somehow.

**Comment by darrenjacoby** [comment]
@osadler @MWDelaney @christianmagill @vdrnn 

I've created a pull request on Sage which would add support for Controller and WooCommerce.  No other code changes or Controller updates would be required.

https://github.com/roots/sage/pull/1914

**Comment by darrenjacoby** [comment]
This issue has been closed on the Sage repo and documentation will be added in time.

**Comment by mtx-z** [comment]
Here is what i needed to do to get variables in all templates : https://discourse.roots.io/t/controller-and-woocommerce/9469/5 - not sure that it is good !
