### ISSUE TITLE
Debug Bar Extension?

### ISSUE THREAD

**Issue by strarsis** [soberwp/controller#18]
This plugin offers some debug functions (https://github.com/soberwp/controller#blade-debugging), 
wouldn't it make sense to add an extension plugin for the [Debug Bar plugin](https://wordpress.org/plugins/debug-bar/)?

**Comment by darrenjacoby** [comment]
Hi @strarsis 

I will take a look at the debug bar and see if extending it is possible for Controllers use case. 

I'm going to close the issue for now.
