### ISSUE TITLE
Naming with hyphens?

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#20]
I see the naming strategy has been changed.

How do you name controllers whose templates include hyphens? For example template-faq.blade.php

Thanks

**Comment by christianmagill** [comment]
Additionally what does the class name become? Thanks

**Comment by darrenjacoby** [comment]
Hi @christianmagill,

You can use the original naming or the new naming. 

The filename and classname for the example you gave would be TemplateFaq.php and classname TemplateFaq 

Essentially it works with camel case now as well.

**Comment by christianmagill** [comment]
I'm having trouble getting camel case to work in a project. Using latest Sage.

template-products.blade.php
TemplateProducts.php
class TemplateProducts

![body-classes](https://user-images.githubusercontent.com/2133370/28687506-a177e94c-72dc-11e7-9f6e-6992103e8607.png)
