### ISSUE TITLE
Non-Sage usage?

### ISSUE THREAD

**Issue by samburgers** [soberwp/controller#21]
Hi, any interest in making Controller compatible with this blade plugin? I have setup a fresh theme with bladerunner and laravel-mix, and was hoping controller would work too :)

https://github.com/ekandreas/bladerunner

edit: using bedrock/trellis still, just not sage

**Comment by darrenjacoby** [comment]
Hi @samburgers 

I know that Toby, who is also active in the Roots community is looking into adapting for non Sage use. I've got the gist and will take a look at possibly working this into Controller.  

I will let you know once I take a look.

**Comment by samburgers** [comment]
unreal, thanks @darrenjacoby !

**Comment by darrenjacoby** [comment]
@samburgers I'm going to close this for now, but I'll be taking a look soon at our possibilities for opening up usage to standard WP installs.
