### ISSUE TITLE
Blade template doesn't work on my Sage 9

### ISSUE THREAD

**Issue by dalenguyen** [soberwp/controller#22]
Hi,  I am testing the plugin on my Sage 9 theme. However, there is a problem that I couldn't find the answer. When I follow the instruct to create an example to expose _$images_ to _resources/views/single.blade.php_

However, my page doesn't recognize the blade template and displays the raw content of the blade instead of showing an error or something like that. 

My code is at: https://github.com/dalenguyen/sage-dn/commit/ab9ed7d73ab096ddff73b29b91d714fde5133819

Sample post with the single.php created in resources/views/single.blade.php

http://edu.dalenguyen.me/blog/2017/05/11/hello-world/

Any thoughts? Thanks,

**Comment by darrenjacoby** [comment]
Hi @dalenguyen 

You're including Controller as a theme dependency.  At the moment it is still a mu-plugin and needs to be used as such. Having said that, I will be changing this repo over to a theme dependency this week. You can watch this repo or follow me on twitter to keep updated when it happens.

**Comment by dalenguyen** [comment]
Thanks @darrenjacoby for your explanation.

**Comment by darrenjacoby** [comment]
@dalenguyen I've scheduled the change from mu-plugin to theme dep for this coming Friday.  

So the code you used should work by end of the week.
