### ISSUE TITLE
Cannot redeclare Sober\Controller\debugger()

### ISSUE THREAD

**Issue by Log1x** [soberwp/controller#23]
It looks like since the update a few hours ago, you setup `autoload` in `composer.json` to autoload the plugin, but are still declaring `"type": "wordpress-muplugin"` thus the plugin is installing into `/mu-plugins/` and being loaded by WordPress as well as Composer resulting in an error.

I can see how this could be overlooked as Sage 9 doesn't ship with `installer-paths` set in `composer.json` like it does Bedrock, but if they are manually set at a theme-level it will result in the error above.

Thanks in advance for a quick fix.

**Comment by darrenjacoby** [comment]
Sorry, that's an oversight. 

Please try del, clear cache and re-install.

**Comment by Log1x** [comment]
Should be good now. Thanks!
