### ISSUE TITLE
Call to undefined function Sober\Controller\add_action()

### ISSUE THREAD

**Issue by iljamm** [soberwp/controller#24]
Just installed controller using 

`composer require soberwp/controller:9.0.0-beta.3`

and getting the following error across the whole project

**Error: Call to undefined function Sober\Controller\add_action() in /srv/www/myproj/current/vendor/soberwp/controller/controller.php on line 36**

**Comment by darrenjacoby** [comment]
Hi @iljamm 

That is strange, I will investigate today and let you know.

**Comment by iljamm** [comment]
Sorry my bad, i installed in a wrong composer file. When I required it in the theme's composer all worked as expected. May be it could be made a tad more prominent in the documentation, which composer file should be used. I realised you said that in the following sentence:
"Please note that Controller is no longer an mu-plugin and is now a Composer theme depedency."

IMHO addition of dummy path to the file would prevent such errors in the future.

**Comment by darrenjacoby** [comment]
Thanks, noted, I will update the README file to make it more obvious.
