### ISSUE TITLE
9.0.0-beta.3 controller.php missing plugin headers - uninstallable

### ISSUE THREAD

**Issue by treyduffy** [soberwp/controller#25]
Can't install beta.3 using any normal methods. 

From Sage 9 empty theme I have no way of updating to beta3. Adding the repository directly to my composer.json will install it into ../../plugins/controller (from inside theme dir), but the controller.php is lacking a plugin header so it won't activate. After manually adding the Plugin header and activating it complains that it's missing dependencies. 

You can't manually install via zip for the same reason. 

Thoughts? I know I'm missing something obvious here, any help would be much appreciated.
```
"repositories": [
    {
      "type": "package",
      "package": {
        "name": "soberwp/controller",
        "type": "wordpress-plugin",
        "version": "9.0.0-beta.3",
        "source": {
          "type": "git",
          "url": "git@github.com:soberwp/controller.git",
          "reference": "master"
        }
      }
    }
  ],
  "autoload": {
    "psr-4": {
      "Roots\\Sage\\": "app/lib/Sage/"
    }
  },
  "require": {
    "php": ">=5.6.4",
    "composer/installers": "~1.0.25",
    "illuminate/view": "~5.4.0",
    "illuminate/config": "~5.4.0",
    "soberwp/controller": "9.0.0-beta.3"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "^2.8.0"
  },
  "extra": {
    "installer-paths": {
      "../../mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "../../plugins/{$name}/": ["type:wordpress-plugin"],
      "../../themes/{$name}/": ["type:wordpress-theme"]
    }
  },
```

**Comment by darrenjacoby** [comment]
@treyduffy Controller is no longer a mu-plugin, it is now a Sage theme dependency. 

You should be able to remove the repositories object in your example above and it should work.
