### ISSUE TITLE
Make "data" property protected instead of private

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#27]
Making the "data" property protected instead of private would make it easier to add data in bulk via the constructor. This would be useful for pulling all ACF fields at once, or pulling in additional data from database or API.

```
public function __construct(){
   $fields = get_fields();
   $this->data = array_merge($fields, $this->data);
}
```

**Comment by darrenjacoby** [comment]
No problem, I will change.

**Comment by darrenjacoby** [comment]
@christianmagill this is in the latest dev-master version.  

https://github.com/soberwp/controller/commit/ea49978b1889f6ab57068e3746a5c4dd5bbafb80

**Comment by christianmagill** [comment]
@darrenjacoby This issue is back again.
