### ISSUE TITLE
Index.php is missing from hierarchy for categoreis

### ISSUE THREAD

**Issue by iljamm** [soberwp/controller#28]
This is the output of hierarchy debugger for one of category pages in one of my projects:

```
/controllers/app.php
/controllers/archive.php
/controllers/category.php
/controllers/category-2.php
/controllers/category-fitness.php
```
I would expect there to be an index.php just above archive.php to comply with the default wp template hierarchy. Is index.php omitted intentionally?

**Comment by darrenjacoby** [comment]
Hey @iljamm , I'll look into this over the weekend.  

As a general rule, app.php does apply to all templates, like index.php would.  

However, app.php is extended to all views by default, whereas I suppose index.php would be overwritten by a more specific template.  Is that the particular use case you are after?

**Comment by darrenjacoby** [comment]
@iljamm Index.php now works for all routes.  Unline App.php, it can be overridden with more specific templates. Closing.
