### ISSUE TITLE
Unable to get variable in blade template

### ISSUE THREAD

**Issue by aaroneight** [soberwp/controller#3]
Sorry for another message!  I tried recreating the single post images example verbatim for the single controller and blade template (including creating an ACF images field).  However, when I go to the single post, it says `Undefined variable: images`.   

When I include `@controller`on the blade template  it outputs the exact same text `@controller`

When I include `@debug`on the blade template it outputs `controller debugger:` and that's it.  

I'm on the latest release and php7.0.15

Any thoughts on how I can troubleshoot this or why my class method is not converting into a variable?

**Comment by darrenjacoby** [comment]
Hi, 

Please could you please send on the exact code you're using and I will be able help. In alpha3 it's @debug(controller) and @debug(dump). @controller has been dropped. It's in alpha so things are bound to change at this stage. 

The method name becomes the variable name in snake case.

**Comment by aaroneight** [comment]
Yes, sorry about that. 

Here is my **controller/page.php**

```
<?php
namespace App;

use Sober\Controller\Controller;

class Single extends Controller
{
    /**
     * Protected methods will not be passed to the template
     */
    protected function hidden()
    {

    }

    /**
     * Return images from Advanced Custom Fields
     *
     * @return array
     */
    public function images()
    {
        return get_field('images');
    }
}
```

And then here is my **templates/page.blade.php**

```
@extends('layouts.base')

@section('content')
  @while(have_posts()) @php(the_post())
    @include('partials.page-header')
    @include('partials.content-page')

    @if($images)
      <ul>
        @foreach($images as $image)
          <li><img src="{{$image['sizes']['thumbnail']}}" alt="{{$image['alt']}}"></li>
        @endforeach
      </ul>
    @endif

  @endwhile
@endsection
```

And here is the notice: 
` Notice: Undefined variable: images`

**Comment by darrenjacoby** [comment]
@aaroneight try rename the controller folder to controllers if you're not redefining the path and let me know.

**Comment by aaroneight** [comment]
I actually am redefining the path in `functions.php`: 

```
add_filter('sober/controller/path', function () {
    get_stylesheet_directory() . 'src/controller';
});
```

**Comment by darrenjacoby** [comment]
I think it's because you're missing a / before src.

**Comment by aaroneight** [comment]
I've tried with a leading / and trailing / and both to no avail. 

I also tried moving the /controllers/ theme root like in the example and disabling custom path, and am still seeing the same error. Hm..

**Comment by darrenjacoby** [comment]
I will do some debugging tomorrow and try to recreate on my end.

**Comment by darrenjacoby** [comment]
@aaroneight, please download 1.0.0-alpha4.  That should resolve all issues.  Sorry about that.

**Comment by aaroneight** [comment]
Still the same issue with alpha4.  

I did disable my custom path and was able to get the variable/s to pass through, however.

**Comment by darrenjacoby** [comment]
@aaroneight I just tested the following and it works as should 

`add_filter('sober/controller/path', function () {
    return get_stylesheet_directory() . '/test';
});`

This may not be the case here, but .blade.php files are cached which has got me a few times working on this, so perhaps edit the .blade.php file and see if it resolves.

**Comment by aaroneight** [comment]
Works for me now.  I think you are right, there was also some caching of the blade files taking place, obfuscating things.  Thanks!
