### ISSUE TITLE
@debug directives print in plain text

### ISSUE THREAD

**Issue by ben-sharp** [soberwp/controller#30]
```Blade
@debug('dump')
@debug('hierarchy')
@debug('controller')
```
Each line in my view outputs in plain text on the page. I am running Sage 9.

Am I missing any instructions other than installing this package in my sage theme directory via Composer?

Please let me know if I can provide any more information that may be helpful, thanks.

**Comment by darrenjacoby** [comment]
Sounds right, how were you expecting the output?

**Comment by ben-sharp** [comment]
As per the readme I was expecting to see the lists echoed out mentioned in the `Blade Debugging` section, but only see the directives themselves being printed. I just have those 3 lines at the top of my view `front-page.blade.php`, is my usage incorrect? I just wanted to see what they produce for future debugging.

Cheers

**Comment by darrenjacoby** [comment]
Hmm, ok, doesn't sound right.  Can you send through a screengrab perhaps, and the code? I will see if I can try to replicate.

**Comment by ben-sharp** [comment]
I took these steps:

- In my `sage` theme folder: `composer require soberwp/controller:9.0.0-beta.3`
- Created directory `themes/sage/resources/controllers/`
- Copied the example `App` controller, named `App.php` inside above mentioned `controllers` directory

Here is a screengrab of my view and controller:
![screen shot 2017-06-29 at 9 09 51 am](https://user-images.githubusercontent.com/7728680/27660355-fe6f93a4-5caa-11e7-89e8-906e7ba3dc6f.png)

And here are my current results:
<img width="1180" alt="screen shot 2017-06-29 at 9 05 29 am" src="https://user-images.githubusercontent.com/7728680/27660405-2609114c-5cab-11e7-9b9c-c36faedfe3b2.png">


Please let me know if I could provide any more helpful info

Cheers

**Comment by darrenjacoby** [comment]
@ben-sharp did you manage to get this working? I haven't been able to recreate.

**Comment by ben-sharp** [comment]
@darrenjacoby pardon the late response, the fault was on my end with a different composer setup.
