### ISSUE TITLE
@debug('dump') style

### ISSUE THREAD

**Issue by 9585999** [soberwp/controller#31]
How do you look at adding styles to debug('dump') and making it look something like this?

![img 2017-07-01 10 42 12](https://user-images.githubusercontent.com/16165904/27760192-2dac5b2a-5e4a-11e7-9c9f-83404a80eea0.PNG)

In this form, the information is more readable ...

**Comment by darrenjacoby** [comment]
@9585999 I've tried to keep the Controller as lightweight as possible. I'll take a look at what would be involved, but would likely prefer sticking with the default var_dump style.

**Comment by 9585999** [comment]
@darrenjacoby These styles do not have to be permanently connected, you can only include them in development, for example, make them dependent on the value of the constant WP_DEBUG, ie if WP_DEBUG === 'true', which is usually done during development, styles are connected, otherwise there are no styles ...
