### ISSUE TITLE
Passing multiple variables from controller function to view

### ISSUE THREAD

**Issue by nathobson** [soberwp/controller#32]
Firstly, thank you SO much for your work on the controller project. It's taking me a little bit to get to grips with it all but slowly getting there!

To help get up to speed with Blade in general, I've been watching the Laracast videos, specifically Laravel 5 Fundamentals. In the video Passing Data to Your Views (https://laracasts.com/series/laravel-5-fundamentals/episodes/4), passing multiple variables within a single function is discussed. I've been trying to decide what the best practice is here but the methods outlined in the video don't seem to work with Sage 9. Is this something to do with the particular implementation of Blade or am I being a super noob?

Before watching this video, this was my methodology:

**resources/controllers/Single.php**

```
public function fields()
{
    $images = get_field('image');
    $description = get_field('description');
    $data = [
        'images' => $images,
        'description' => $description
    ];

    return $data;
}
```
**resources/view/contact.blade.php**
```
<ul>
    @foreach($fields['images'] as $image)
        <li><img src="{{$image['sizes']['thumbnail']}}" alt="{{$image['alt']}}"></li>
    @endforeach
</ul>

<p>{!! $fields['description'] !!}
```
This works fine but is a bit more verbose than the implementation within the Laracast videos and also requires manually building an array of all of the required variables. In the videos, they pass variables to the `view` function within the controller, which are then passed to the view:

Controller:
```
public function about()
{
    $first = 'Fox';
    $last = 'Mulder';

    return view('pages.about', compact('first', 'last'))
}
```

or:
```
public function about()
{
    data = [];
    $data['first'] = 'Fox';
    $data['last'] = 'Mulder';

    return view('pages.about', $data)
}
```
**View**
`<h1>About Me {{ $first }} {{ $last }}</h1>`

Can we do something similar or is there even a better way for the Sage 9 implementation? I guess the other option is to build many different functions within the controller but then the tradeoff seems to be that the view are cleaner but the controller much more verbose.

**Comment by nathobson** [comment]
I guess the first example could be shortened to (controller):

```
public function fields()
{
    $data = [
        'images' => get_field('image'),
        'description' => get_field('description')
    ];

    return $data;
}
```

**Comment by darrenjacoby** [comment]
Sorry @nathobson, I've been on vacation.  That looks right to me.

If you're in a loop then you can use https://github.com/soberwp/controller#using-static-methods
