### ISSUE TITLE
Without Sage

### ISSUE THREAD

**Issue by 3runoDesign** [soberwp/controller#33]
Is there any way to use without Sage?

I can use it by changing the lines:
https://github.com/soberwp/controller/blob/master/controller.php#L13
https://github.com/soberwp/controller/blob/master/controller.php#L26

**Comment by darrenjacoby** [comment]
I am open to a PR for adding this functionality.  I know there has been some interest from others to add. Alternatively I could look into it in the next month or so.

**Comment by darrenjacoby** [comment]
Closing for now.
