### ISSUE TITLE
Controllers direcory

### ISSUE THREAD

**Issue by thomascharbit** [soberwp/controller#38]
Just a thought, but shouldn't the `controllers/` directory be by default under `app/`?
So `app/controllers/` instead of `resources/controllers`, like Laravel does?

I know there is a filter for this, but i see that this package is now shipped with Sage 9, and because Sage seems to follow Laravel philosophy and file structure, why would it be under `resources/`?

Thanks!

**Comment by darrenjacoby** [comment]
@thomascharbit 

I agree. I will change the default folder over the weekend for dev-master.

**Comment by thomascharbit** [comment]
Awesome, thanks
