### ISSUE TITLE
[doc] enqueue?

### ISSUE THREAD

**Issue by strarsis** [soberwp/controller#41]
For a sage9 based theme, does it make sense to enqueue script/style for a particular page in controller?

**Comment by Log1x** [comment]
You should stick to Discourse for questions like this man. This is an **issue** tracker.

**Comment by darrenjacoby** [comment]
Yeah, this is more of a feature request. I do feel that Controller should only handle data and not go into enqueuing scripts. I'm open if there are +1's, but closing for now.
