### ISSUE TITLE
Use __construct() to add_action()

### ISSUE THREAD

**Issue by mtx-z** [soberwp/controller#42]
Hello !

First of all, really nice Job on this together with Sage ! We finally have the "VC" of "MVC" in Wordpress !
I am trying to add_fonction() from my controllers. I thought the best way doing this was to use the __constructor() method. 
But unfortunatly, the Controller is instanciated multiple time (in my case taxonomy-product_cat for Woocommerce), and so the action is added multiple time wich is not good.

I found a way to prevent this, but I don't think that this is a good way, more of a "tweak".

```
class TaxonomyProductCat extends Controller
{
    private static $trigger = 0;

    public function __construct()
    {
       /* if (!self::$trigger) {
            $this->add_product_content_data();
            //add_action('woocommerce_after_shop_loop_item_title', [$this, 'add_actions_filters'], 9);
            self::$trigger++;
        }*/
    }

    public function add_actions_filters()
    {
        if (!self::$trigger) {
            add_action('woocommerce_after_shop_loop_item_title', function() {
                echo('<p>oks</p>');
            }, 9);
            self::$trigger++;
        }
    }

    public function term()
    {
        return get_term_by('slug', get_query_var('term'), get_query_var('taxonomy'));
    }
}
```

As you can see, I tried first putting the add_action() into the __constructor method. with a callback [$this, 'add_product_content_data'] to call a controller method that do a "echo()". But this was not working as the controller is used to populate variables to be binded to the view, and so was directly "echoing" on top of the site because, well there is a "echo" and i dont return nothing.

So i moved the add_action to a method that is triggered once, even if controller is instanciated multiple time. And as all controller methods are called to bind data to the view, this work. 

Is there a better way to do this ? 

Thanks !

**Comment by darrenjacoby** [comment]
Hi @mtx-z 

Hmm, interesting use case.  Essentially Controller was designed around data, and not hooks, so not much testing has happened in that area. I know there are still a few issues to work out with WooCommerce, from likely both Sage and Controller sides.

Two options you could try, but I have not tested these, just initial thoughts.

- Use `protected function add_actions_filters()` and `protected function term()`. Remember that any `public function` is being run by Controller automatically in an attempt to convert to a variable for Blade. Using `protected function` does not run the function unless called, which you are doing above in `__construct`

- You could also try to use a `protected function functionName` and removing `__construct` altogether. You could then run this from the view using {{ TaxonomyProductCat::functionName() }}. I have not tested this so may not work. 

Lastly, for the M in MVC, https://github.com/soberwp/models may interest you.

**Comment by mtx-z** [comment]
Hi @darrenjacoby,

thanks for your answers. 
Yes i saw that Controller was not designed exactly for what i wanted to do, but not impossible !

I like your approach, specially the protected method. 

- With the protected method, i could trigger it from the __constructor, but again, with a add_filter/action, as controller is instanciated multiple time, I would see my filter/action added multiple time. That is what i "hacked" a way to trigger it only once. In the end, the __constructor() triggering a protected method() will produce same amount of "add_filter" as using a public method() (public method() called at every instanciation, __construct() also)

- The last solution, call from template, should work as expected. As the method will be called once. But i really wanted to put all business part in controllers, to enjoy the "VC" you add to WP :) 

- I tried to make a BaseController to extend mine, and add the self::$trigger globally, but failed as my BaseController class is never found when trying to extend my specific controllers with it. 

- not related, but here i found a "way" to correctly bind all variables to sub woocommerce views (https://discourse.roots.io/t/controller-and-woocommerce/9469/5) - but had a issue overriding single-product and so had to tweak to change a path. No problem with archive-product.php, strange. Issue come from the override. 

Thanks again !

**Comment by darrenjacoby** [comment]
Cool thanks for the feedback, I'm going to test this later with an add_action and see what I come up with. It should only be firing once though, not sure why it's firing twice.

**Comment by mtx-z** [comment]
Well, from what I see, it's because controllers are triggered multiple time. So it's not a problem for returning value (if we dont see the performance layer), but it is for add filter/action.
For example, i saw that my taxonomy controller was instanciated twice. 
And the App Controller, 6 or 7 time. 

IDK if default, or because of my Woocommerce updates in single-product and archive-product to bind variables that causes this behavior.

**Comment by darrenjacoby** [comment]
@mtx-z 

Using PSR4 autoloading, which will be pushed to dev-master soon, may fix this issue. 

I'll do some local testing to see.

**Comment by mtx-z** [comment]
Good news !
This way we can move all the specifics action/filter into our controllers properly.

Waiting for the release ! Thanks for the update @darrenjacoby.

**Comment by Log1x** [comment]
Any update on fixing how controllers are triggered? I'm also having some issues with this.

As far as using `__construct()` to load actions-- that would be kind of nice. I find that while at the initial release of Controller I used a lot of normal functions and simply returned data-- my codebase now has vastly more logic to it and I pretty much solely use `public static function`'s now.

One problem I'm having is I have a `public static function` to create a cookie but it gets set in the HTTP headers like 20 times...

I tried switching it to a `protected function` and loading it with `add_action('init', [$this, 'setSource']);` as well as:

```php
add_action('init', function () {
    wp_die('test');
    return self::setSource();
}, 11);
```

but not even my `wp_die();` would fire no matter what priority I did the `init` at.

:frowning:

**Comment by darrenjacoby** [comment]
Hey @Log1x 

I'll check it out tomorrow. I think PSR4 loading will solve this, but would need to test and confirm.

**Comment by darrenjacoby** [comment]
Just checking out Laravel, it might make sense to build a ServiceProvider for Sage thinking about it.

**Comment by oscar-g** [comment]
I had a similar problem and I found the App controller was being constructed twice. 

Because the calls `add_action` were in App::__construct, and App was being constructed twice, the action handler was  registered twice.

Here is my patch for it...maybe not the most efficient, but it seems to fix the issue for me.  It definitely needs testing on more complicated sites.

https://github.com/oscar-g/controller/commit/c1ef79dc24f5a2ad7b0d84990ff6186d713cc02b

Compared with soberwp/controller@master:

https://github.com/soberwp/controller/compare/master...oscar-g:dev-run-just-once

**Comment by oscar-g** [comment]
@darrenjacoby, I'm curious about PSR4. How can we use it to solve this problem?

**Comment by darrenjacoby** [comment]
@oscar-g @Log1x @mtx-z 

Just pushed PSR-4 to dev-master. It does appear to fix the multiple executions. Let me know if it works your side.

https://github.com/soberwp/controller/commit/93aa3ccd869b6092eefb941e342382ce7e3b00db

Regarding adding add_action to Controllers, I'm not sure it will work. I also don't feel like that should be in a Controller, a ServiceProvider would be more appropriate. I need to pass everything via this filter below, which would be set up after add_action. 

```
add_filter('sage/template/' . $template . '-data/data', function ($data) use ($loader, $class) {
        $controller = new $class();
        $controller->__setup();
        return array_merge($loader->getAppData(), $loader->getPostData(), $controller->__setTreeData($data), $controller->__getData());
});
```
