### ISSUE TITLE
$__currentLoopData

### ISSUE THREAD

**Issue by 9585999** [soberwp/controller#43]
Hi, is there any sense in these variables in the **Controller Debugger**?

![img_2017-08-26_ _10_32_24](https://user-images.githubusercontent.com/16165904/29739749-f2a8ca4c-8a4d-11e7-85aa-686d58436610.png)

As I understood for the conclusion of similar things the function `sanitize()` answers, can it be necessary to it to fasten the filter, or something like this, so that it would be possible to optionally remove unnecessary variables?

For example, the **$query** variable that is defined in the template, I do not need in 99% of cases, but it is with a huge list of arrays ... The variable **$term** also makes no sense in the debugger, since this is one element of the array **$terms_category**, which can be so Peep at **$terms_category** ...

**Comment by darrenjacoby** [comment]
Hey @9585999 

Interested to know how you got those variables there? Is this within a category/term loop/query?

**Comment by 9585999** [comment]
@darrenjacoby Here is an example of the code that gives these variables:
```blade
@php($terms_category = get_terms([
    'taxonomy' => 'category-services',
    'order' => 'ASC',
    'orderby' => 'name',
]))


@foreach ($terms_category as $term)

  @php($query = new WP_Query([
    'post_type' => get_post_type(),
    'tax_query' => [[
        'taxonomy' => $term->taxonomy,
        'field' => 'term_id',
        'terms' => $term->term_id,
      ]],
    'order' => 'ASC',
    'orderby' => 'name',
  ]))

  <section class="{!! $term->taxonomy . '-' . $term->term_id !!}">
  <h2 class="entry-title">{!! $term->name !!}</h2>
  <p class="lead">{!! $term->description !!}</p>

    @while ($query->have_posts()) @php($query->the_post())
      @include('partials.content-'.get_post_type())
    @endwhile
  </section>

  {!! wp_reset_postdata() !!}
@endforeach
```
It displays on the page the terms of category-services with posts:
* **Title Category-Services Term-1**
category-services term-1-description
    * post > (term-1)
    * post > (term-1)
    * post > (term-1)
* **Title Category-Services Term-2**
category-services term-2-description
    * post > (term-2)
    * post > (term-2)
    * post > (term-2)
* **Title Category-Services Term-3**
category-services term-3-description
    * post > (term-3)
    * post > (term-3)
    * post > (term-3)

**Comment by darrenjacoby** [comment]
@9585999 

Just want to make double sure, the new Debugger commits in the PR would resolve this, right?

**Comment by 9585999** [comment]
@darrenjacoby yes.

With this filter, you can remove variables from the debugger that you do not want to see in the debugger ...

```php

add_filter('sober/controller/debugger/sanitize', function ($data) {
    $data = collect($data)->except([
        'loop', 'query', 'term', '__currentLoopData'
    ])->all();

    // or
    // $data = array_diff_key($data, array_flip(['loop', 'query', 'term', '__currentLoopData']));

    return $data;
});
```

**Comment by darrenjacoby** [comment]
Nice! I'm going to play with it over the weekend and then merge. 

I'd like to see if it could be to simplified further for the user, so that the filter only includes something like this; 

```
add_filter('sober/controller/debugger/sanitize', function () {
  return ['loop', 'query', 'term', '__currentLoopData'];
});
```

I also think that __currentLoopData should be removed by default, so I'll add that in via Controller itself.

**Comment by 9585999** [comment]
@darrenjacoby How do you like this option?
```php

$sanitize = ['__env', 'app', 'obLevel', '__currentLoopData'];
$data = has_filter('sober/controller/debugger/sanitize') ? array_merge($sanitize, apply_filters('sober/controller/debugger/sanitize', $data = [])) : $sanitize;
$this->data = array_diff_key($this->data['__data'], array_flip($data));

# Use
 add_filter('sober/controller/debugger/sanitize', function () {
     return ['loop', 'term', 'query'];
 });
```

**Comment by darrenjacoby** [comment]
@9585999 

That's so clean!  Love that.

**Comment by 9585999** [comment]
@darrenjacoby just wanted to write that you can insert the check 😄

**Comment by 9585999** [comment]
@darrenjacoby I think somehow so
```php

$sanitize = ['__env', '__currentLoopData', 'app', 'obLevel'];
$data = apply_filters('sober/controller/debugger/sanitize', $sanitize);
$data = is_array($data) ? $data : [$data];
$data = has_filter('sober/controller/debugger/sanitize') ? array_merge($sanitize, $data) : $sanitize;
$this->data = array_diff_key($this->data['__data'], array_flip($data));
```

**Comment by darrenjacoby** [comment]
@9585999 

Cool, no problem!

**Comment by 9585999** [comment]
@darrenjacoby no problem! Again!

**Comment by webstractions** [comment]
The `$loop` variable is added by Blade when you use a looping directive such as `@foreach`. That variable provides information such as the current loop index and whether this is the first or last iteration through the loop. Not really sure if anyone really has a need for the variable and it can probably be excluded along with `__env`, `__currentLoopData`, as well.

**Comment by darrenjacoby** [comment]
I've been rewriting debugger to pass on more valuable information (such as static methods, data override notices, etc), and that only provides Controller information. By doing so, I'm using a different approach that negates the underscore issue entirely. Closing for now.
