### ISSUE TITLE
Switching to 9.0.0-beta4 and back to dev-master break Sage integration

### ISSUE THREAD

**Issue by mtx-z** [soberwp/controller#44]
Hey !

I just tried to update the package to `9.0.0-beta4`, and it broke the installation.
So i switched back to `dev-master`, and it didn't fixed the issue. 

I add to add in my `function.php` (or included, `filters.php` for Sage)
```
add_filter('sober/controller/path', function () {
    return dirname(get_stylesheet_directory()) . '/resources/controllers';
});
```

again to match Sage 9 Beta Controller location.

Thanks !

**Comment by darrenjacoby** [comment]
Can you try the following

```
add_filter('sober/controller/path', function () {
    return get_stylesheet_directory() . '/resources/controllers';
});
```

**Comment by mtx-z** [comment]
The filter I added work already. 
It was just to notify that update and downgrade can cause the error on Sage, and so need the filter (back?) to work. I had no issue after a fresh Sage install.

**Comment by darrenjacoby** [comment]
thanks, I will take a look.

**Comment by 9585999** [comment]
@mtx-z if I'm not mistaken then `get_stylesheet_directory()` returns **$path/resources**

You need to add only `/controllers`, if you want to place a folder **controllers** In `resources/`, filter should look like this:

```php
add_filter('sober/controller/path', function () {
    return get_stylesheet_directory() . '/controllers';
});
```

**Comment by darrenjacoby** [comment]
That's what I meant to comment with, haha. 

@9585999 thank you

**Comment by darrenjacoby** [comment]
@mtx-z I do see this issue as more of a teething problem than something that should be solved with additional code. Moving forward, with the correct versions, this should not be an issue.
