### ISSUE TITLE
Sage - SoberWp Controller - {! App::title() !} in blade view is not working

### ISSUE THREAD

**Issue by jajouka79** [soberwp/controller#47]
https://discourse.roots.io/t/sage-soberwp-controller-app-title-in-blade-view-is-not-working/10326

I have raised this issue here already. sage with controller is not working out of the box~

I have just installed the latest version of sage that uses the soberwp controller package, after running composer install and yarn as instructed in docs I get this error on the site home page:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found ....

ErrorException: Class 'App' not found (View: /srv/www/xxxxxxx.org/current/web/app/themes/sage-controller/resources/views/partials/page-header.blade.php) (View: /srv/www/xxxxxxx.org/current/web/app/themes/sage-controller/resources/views/partials/page-header.blade.php) in /srv/www/xxxxxxx.org/current/web/app/uploads/cache/b86c51c4f6669655bff05894c46da3bddd3b03b4.php on line 2
```

I thought the controllers weren’t loading but in vendor/composer/autoload_psr4.php this line exists:

`'App\\' => array($baseDir . '/app'),`

maybe the contollers/helpers are not accessible to the blade views

any help would be appreciated, thanks

**Comment by 9585999** [comment]
@jajouka79 Strangely, I just installed the theme sage, I have everything working ...


![kapture 2017-08-31 at 15 13 22](https://user-images.githubusercontent.com/16165904/29922685-4a142f46-8e5f-11e7-9cfa-ebe080c54a1f.gif)

**Comment by darrenjacoby** [comment]
It may be cache related. Not finding App is often a location issue with the Controller files. From 9.0.0-beta.4 the default path is `app/controllers`. Also worth making sure that it's not using any cached version. If you change app/controllers to `resources/controllers`, does it work? If so, then my first guess would be that it is cache related.

**Comment by greatislander** [comment]
@darrenjacoby As per [my Discourse post](https://discourse.roots.io/t/controller-doesnt-work-when-installing-sage-based-theme-via-composer/10272/10) in Discourse, I get this behaviour when I load a sage-based theme into Bedrock via Composer (and https://github.com/soberwp/controller/ is placed in  `/site/vendor/` instead of `/site/web/app/themes/sage-based-theme/vendor/`. I note your comment about load order and PS-4 on [this](https://discourse.roots.io/t/best-practice-resources-for-blade/8341/135) Discourse thread; I wonder if it's related?

**Comment by jajouka79** [comment]
thanks for the replies, if it is cache related, how do I fix it? how do I clear the sage cache?

**Comment by jajouka79** [comment]
also in phpstorm the offending line of out the box code {! App::title() !} in page-header.blade.php has App highlighted as an error, the program can't find it

**Comment by darrenjacoby** [comment]
@greatislander Controller is no longer a plugin dep. It usually to be included with Bedrock Composer, and placed as a mu-plugin. This is no longer the case, it is now a package that needs to be required from within the Sage theme dir.

**Comment by darrenjacoby** [comment]
@jajouka79 have you tried changing the Controller location to `resources/controllers` to test?

**Comment by greatislander** [comment]
@darrenjacoby I'm aware of that. My question is how do you make a theme that is based on Sage available for installation via Composer? Do you have to commit the `/vendor` directory? That doesn't seem like a good practice.

**Comment by Log1x** [comment]
You don't have to commit `/vendor` if you are making it available via Composer as Composer will install all the dependencies for you.

**Comment by greatislander** [comment]
@Log1x Does Controller work for you when Composer installs it in bedrock's `/vendor/` folder? It doesn't for me. That's what I'm saying…

**Comment by darrenjacoby** [comment]
It shouldn't be in Bedrocks `vendor/ `folder though, it should be in the Sage `vendor/` folder. As @Log1x said, don't commit `vendor/`, Composer will install deps.

**Comment by darrenjacoby** [comment]
@greatislander
 
Just checking if you've managed to get it working? Otherwise I will set up a Bedrock instance and test, but would prefer to spend time on adding a feature to Controller.

**Comment by jajouka79** [comment]
sorry folks my problems is that I had soberwp/controller in my project composer.json file as well as in the sage theme. i removed that and it worked, thanks for your help

**Comment by darrenjacoby** [comment]
@jajouka79 glad to hear!

**Comment by greatislander** [comment]
Hi @darrenjacoby, Controller does work wonderfully when it's in the Sage `/vendor` folder. That's not the issue. In my use case, I want to be able to make a Sage-based theme which can be distributed for anyone to install via Composer in a Bedrock environment (see these two repos which I created to demonstrate: http://github.com/bight/bedrock-controller and http://github.com/bight/sage-controller).

I understand that the way Controller works right now this isn't possible, but I think it's desirable so that users can treat a Sage-based theme like any other Composer dependency.

Whether or not you decide to address this, thanks for all your contributions to the community. Love the Sober WP projects.

**Comment by darrenjacoby** [comment]
@greatislander 

Cool, got you. In a Bedrock environment, does Sage not install dependencies within it's theme folder anyway? For example, Blade, etc which are required. Just trying to understand the difference between that and Controller for example. 

It would be possible to create a branch that allows it to work using Bedrocks composer.json with fairly minimal changes, but just want to make sure I understand the use case, else it may end up confusing users more.

**Comment by greatislander** [comment]
@darrenjacoby In my understanding (and in my testing), installing a Sage theme in a Bedrock environment by adding it to Bedrock's `composer.json` (as opposed to the ["normal" method](https://github.com/roots/sage/#theme-installation) of using `composer create-project roots/sage themename dev-master`) installs all the dependencies (Blade and so forth) in Bedrock's `vendor` directory. This seems to be in line with the Composer docs which [say](https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies):

> Composer… resolves all dependencies listed in your `composer.json` file and downloads the latest version of their files into the `vendor` directory in your project. (The `vendor` directory is the conventional location for all third-party code in a project).

I think to get Composer to install dependencies elsewhere you need to specify a different package type and location, e.g. https://github.com/roots/bedrock/blob/master/composer.json#L47-L51

Thanks, and let me know if I can help with this in any way (testing, etc.).

**Comment by darrenjacoby** [comment]
@greatislander 

Thanks, that makes sense now! I'll look into what can be done here to get it working as a Bedrock package dep.
