### ISSUE TITLE
Controller as Bedrock dep

### ISSUE THREAD

**Issue by darrenjacoby** [soberwp/controller#48]
Noted and looking into https://github.com/soberwp/controller/issues/47#issuecomment-326583876

**Comment by schrapel** [comment]
@darrenjacoby any update on this?

**Comment by darrenjacoby** [comment]
Hey @schrapel not yet but still on the todo. 

I'm moving over the next two weeks so a little crazy this side.

**Comment by greatislander** [comment]
Hi @darrenjacoby, had a chance to look at this yet? Let me know if I can assist in any way.

**Comment by darrenjacoby** [comment]
Hey @greatislander 

Not yet, sorry, I've been in the process of renovating and moving so it's been occupying a lot of my time. I am open to any solutions via PR's on the issue of course, but otherwise I will attempt to take a look before next week.

**Comment by greatislander** [comment]
Understood, thanks!

**Comment by darrenjacoby** [comment]
I'm looking into this, but when Controller is in the Bedrock `vendor/` folder, it loads before WordPress wp-load.php, meaning `add_action` is undefined, therefore this section of coding isn't running—

```php
if (function_exists('add_action')) {
    add_action('init', __NAMESPACE__ . '\loader');
    add_action('init', __NAMESPACE__ . '\debugger');
}
```

I actually think @schrapel answer above is the best way to address this. I can create an soberwp repo for this if you'd like?

**Comment by greatislander** [comment]
I guess my expectation from this feature request had been that there should be a way to install a theme with Controller via Bedrock, and while the companion mu-plugin fix offered by @schrapel does make it work, it’s not ideal (it would almost make as much sense to install Controller as a plugin for themes that need it if that additional dependency is required). But if there’s no other solution a repo that handles this would be good. Perhaps it’s not a common enough use case to warrant that, though.

**Comment by darrenjacoby** [comment]
Closing for now, but may revisit down the line once I've released class dep injection, etc.

**Comment by schrapel** [comment]
I personally feel like that’s a bad decision. You are trying to load something before WordPress that is a dependency of WordPress

**Comment by darrenjacoby** [comment]
@schrapel yeah, that's kind of where I arrived at when testing.

**Comment by ouun** [comment]
Solved it for me as well. Thanks and I'm looking forward for a more robust and non critical solution. 👍

**Comment by mcaskill** [comment]
I solved this issue with a [Composer plugin](https://packagist.org/packages/mcaskill/composer-exclude-files) I created for excluding files from the 'files' autoloading mechanism.

`/composer.json`
```json
"require": {
    "mcaskill/composer-exclude-files": "^1.0",
    "soberwp/controller": "^2.0"
},
"autoload": {
    "exclude-from-files": [
        "soberwp/controller/controller.php"
    ]
}
```

Afterwards, you can either include that bootstrap file from your theme or a plugin.

`/www/themes/<theme>/resources/functions.php`
```php
require VENDORPATH . '/soberwp/controller/controller.php';
```
