### ISSUE TITLE
Naming with underscores

### ISSUE THREAD

**Issue by matbrady** [soberwp/controller#49]
Sorry if this issue already exists. The only similar one I was able to find was #20.
## Problem 
Controller loading doesn't occur with custom post types using underscores. 
**Example**: `resource_collection`

## Details
I have a custom post type of `resource_collection`. It's relevant files include:
- **view** `resources/views/partials/content-single-resource_collection.blade.php` 
- **controller** `app/controllers/SingleResourceCollection.php`
  ```
  <?php
  namespace App;
  use Sober\Controller\Controller;

  class SingleResourceCollection extends Controller
  {
  . . . 
  ```
### Hierarchy Debugger:
```
controllers/app.php
controllers/index.php
controllers/singular.php
controllers/single.php
controllers/single-resource_collection.php
```

Thanks for any help/clarification!

**Comment by darrenjacoby** [comment]
I will see what we can do here and let you know.

**Comment by zacksmash** [comment]
Bump on this. Ran into the same issue.

**Comment by sulfo** [comment]
Aaaaand the same here.

**Comment by darrenjacoby** [comment]
Just a note that I am looking into this.

**Comment by garethpbk** [comment]
Same problem here, I'm using the Single.php controller for now.  Thanks for looking into it!

**Comment by webstractions** [comment]
How about something like this?

**Add $template property to Sober\Controller\Controller**
```php
<?php

namespace Sober\Controller;

class Controller
{
    protected $active = true;
    protected $tree = false;
    protected $data = [];
    
    // Default is null (not set)
    protected $template = null;

    ...

    public function getTemplate() {
        return $this->template;
    }
}
```
**controller.php loader() function**
```php
function loader()
{
    $loader = new Loader();
    foreach ($loader->getData() as $template => $class) {

        if($class->getTemplate()) {
            $template = $class->getTemplate();
        }
        // Pass data filter
        add_filter('sage/template/' . $template . '-data/data', function ($data) use ($loader, $class) {
            $controller = new $class();
            $controller->__setup();
            return array_merge($loader->getAppData(), $loader->getPostData(), $controller->__setTreeData($data), $controller->__getData());
        });
        // Class alais
        class_alias($class, (new \ReflectionClass($class))->getShortName());
    }
}
```
Now you can over-ride the template name inside of your controllers.

```php
class SingleResourceCollection
{
    protected $template = 'partials/content-single-resource_collection';
}
```

**Comment by zacksmash** [comment]
That looks great! Nice solution!

**Comment by darrenjacoby** [comment]
Earlier versions of Controller had the option to specify the template. I think that is the best solution for underscores. I'll add this to dev-master.

**Comment by webstractions** [comment]
@darrenjacoby You're welcome.

**Comment by alwaysblank** [comment]
@webstractions's solution works great! Had to make one tweak to get it there, though:

```php
$instance = new $class; // instantiate class...
if ($instance->getTemplate()) { // ...so we can access its methods
      $template = $instance->getTemplate();
}
```

Without that, I got errors about trying to call a method on a string. Works like a charm now, though! Thanks!

**Comment by webstractions** [comment]
@alwaysblank Looks good! Updated loader() code above to match.

**Comment by darrenjacoby** [comment]
I'll be adding this to dev-master soon.
