### ISSUE TITLE
Custom template controller issues.

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#5]
I've been running into issues with custom templates. Whether I am relying on naming the controller the same or setting the template property, the controller fails to send data to the view.

However, the standard page controller does send it's data.

Thanks for any help you can provide!

templates/faq.blade.php
```
{{--
  Template Name: Frequently Asked Questions
--}}

@extends('layouts.base')

@section('content')
  @while(have_posts()) @php(the_post())
  @include('partials.page-header')
  @include('partials.content-page')
  @endwhile
  {{ $faq or 'No $faq variable returned' }}<br/>
  {{ $page or 'No $page variable returned' }}
@endsection
```

controllers/faq.php
```
<?php
namespace App;
use Sober\Controller\Controller;

class Faq extends Controller
{
    /**
     * Protected methods will not be passed to the template
     */
    protected function hidden()
    {

    }
    public function faq()
    {
        return 'Testing FAQ Controller';
    }
}
```

controllers/page.php

```
<?php
namespace App;
use Sober\Controller\Controller;

class Page extends Controller
{
    /**
     * Protected methods will not be passed to the template
     */
    protected function hidden()
    {

    }
    public function page()
    {
        return 'Testing Page Controller';
    }
}
```

Outputs

```
No $faq variable returned
Testing Page Controller

```

**Comment by darrenjacoby** [comment]
@christianmagill thanks for flagging this.  

The controllers essentially work using the body class, so as a workaround you could add this to the controller; 

```php
<?php

namespace App;

use Sober\Controller\Controller;

class Faq extends Controller
{
    public $template = 'page-template-faq-blade';

    public function faq()
    {
        return 'Testing FAQ Controller';
    }
}
```

I'd like to improve this solution in the next release which I'll be working on this weekend, so I'm going to keep the issue open for now.

**Comment by darrenjacoby** [comment]
I've just released 1.0.0-alpha6 which should address this.  Your original setup should now work.  

I've also added in a singular.php controller option as I use that often, or you could use base.php within controllers/ for global options. 

https://github.com/soberwp/controller/commit/d200c7e448777ee0b21a20c6f180f8e8147d3cf2#diff-3864ffe37f3a1de39876ea62cae525f3

**Comment by christianmagill** [comment]
Thanks for the information and fix!

If the controllers work on the body classes, why not just make this more transparent in the documentation and property name. It's similar to the way Sage handles their javascript routing.

In reality the way you describe the template/controller connection is not exactly right. For instance, a custom page template, with it's own controller, will still incorporate the standard page controller.

This could be useful in many contexts but confusing if it is not expected. I am not sure what happens when two applied controllers have the identically named methods.

**Comment by darrenjacoby** [comment]
@christianmagill sure, it's still in alpha so there's a bit to work through to be honest. I'm working on some changes this weekend and will be testing multiple scenarios and the best way to deal with them. I will update the docs once it's in beta (hopefully soon).

**Comment by christianmagill** [comment]
Thanks! I appreciate your work on this. I think it's going to be great. Let me know if there's anything I can do to help.

**Comment by darrenjacoby** [comment]
I will keep this issue open for now, appreciate your feedback so far, will let you know when the next alpha is released.

**Comment by darrenjacoby** [comment]
@christianmagill I rewrote large amounts of the plugin today.  

I realised that going having template overrides is a bad idea as it quickly becomes a tangled mess. 

I've implemented a more sane structure, while still allowing components through traits.

Here's an implementation example;

 

```php
<?php

namespace App;

use Sober\Controller\Controller;

class Single extends Controller
{
    use Images;

    public function books()
    {
        return array();
    }
}
```

**Comment by christianmagill** [comment]
How is the determination made as to which templates load which controllers? Is it just anything that is a body class? Thanks for your work on this. I'm out tonight but will test out tommorow.

**Comment by christianmagill** [comment]
Okay, I noticed updated documentation in read me and that helped clear up some things. 

The only thing I'm not completely clear on is "Inheriting the Tree/Heirarchy". Where do these co trollers come from and do they stack on top of each other according to the template hierarchy. You mention singular, but there is no "singular" in the template hierarchy. Is thay in reference to the associated body class. Thanks. I really like how things are setup!

**Comment by darrenjacoby** [comment]
@christianmagill it works on the filename.  If there is a faq.blade.php within templates, then faq.php would work.  

I will be testing the Tree more today and will provide more examples.  Essentially it's going to aim at following this, https://developer.wordpress.org/files/2014/10/template-hierarchy.png

So if you had templates/single.php and templates/page.php, you could use controllers/singular.php to send to both (the same as WordPress' standard hierarchy).

**Comment by darrenjacoby** [comment]
@christianmagill the standard WordPress hierarchy has been implemented in 1.0.0-beta1.  If you inspect the body class on a page, you will notice *-data classes;

![image](https://cloud.githubusercontent.com/assets/15921694/23352344/3f77b7dc-fccf-11e6-844a-7f40368ed717.png)

All classes with *-data can become controller files (omitting -data from the filename), with the latest one always overriding the previous should you not add "implements Tree" to the Class declaration.  

I'll update the docs later to better explain.

**Comment by christianmagill** [comment]
Great. I was unfamiliar with the addition of singular.php to the template hierarchy which caused some confusion. The way you have things setup seems very powerful and well organized. Can't wait to try it out.

**Comment by mtx-z** [comment]
Hey there ! 
Just found this issue related to mine. 

I'm using latest Beta, and i'm wandering if there's a way to use a Class attribute
like
`public $template = 'page-template-faq-blade';`

To override the controller search based on controller filename ? 
It would be just to : 
- Have clear controllers filename
- Be able to specify in the controller the "slug" that this controller will match, in addition to its filename. 

Thanks !
