### ISSUE TITLE
Dependency Injection?

### ISSUE THREAD

**Issue by Benjyclay** [soberwp/controller#50]
Is there a way to inject dependencies into a Controller?

**Comment by darrenjacoby** [comment]
@Benjyclay can you give me an example of what you're trying to accomplish?

**Comment by Benjyclay** [comment]
```
class ClassOne extends Controller {
    private $classTwo;

    public function __construct(ClassTwo $classTwo) {
        $this->classTwo = $classTwo;
    }

    public function getSomeStuf($store) {
        return $this->classTwo->getSomeStuff();
    }
}
```

**Comment by darrenjacoby** [comment]
Hm, not sure this is making sense to me. Are you trying to pass a Class in, using __construct?

**Comment by indrek-k** [comment]
@darrenjacoby yes - in the example above, an instance of ClassTwo is injected into the constructor of the controller at the moment it is instantiated. Being able to do something like this is really important for clean architecture, as you'd no longer need to hardcode any external dependencies into the controller class.

I recommend looking into Laravel's DI container (which is used by Sage anyway): https://laravel.com/docs/5.5/container - I assume this would be the cleanest way to set it up. If it was possible to use autowiring to inject dependencies, it would make the controller class much more powerful.

**Comment by mtx-z** [comment]
What type of class would you want to inject here ? 
As i just tested by injecting another Controller, and it works the laravel Way. 
```
use \App\Home; //another controller

class MyController extends Controller {

	private $test;

	public function __construct(Home $home) {
		$this->test = $home;
	}

	public function myMethod() {
		return $this->test->omagad(); //public method from Home Controller
	}
}
```

**Comment by mtx-z** [comment]
+1 would be cool. 

Actually, I can achieve the same result as Laravel do, but it's "dirty code" :) 

use \App\Home;

/**
 * Class ConstruisezVotreParcours
 * @package App
 */
class ConstruisezVotreParcours extends Controller {

	private $test;

	public function __construct() { //no real injection
		add_action( 'wp_ajax_nopriv_getRelatedJobsAsync', [ $this, 'getRelatedJobsAsync' ] );
		add_action( 'wp_ajax_getRelatedJobsAsync', [ $this, 'getRelatedJobsAsync' ] );
		$this->test = new Home(); //dirty
	}

	public function ficheMetier() {
		$query = new \WP_Query(
			[
				'post_type'   => 'metier',
				'post_status' => 'publish',
				'order'       => 'asc',
				'orderby'     => 'title'
			]
		);

		return $this->test->myHomeMethod();
	}

}

**Comment by darrenjacoby** [comment]
I'll see what I can do here to try clean this up!

**Comment by darrenjacoby** [comment]
@indrek-k yeah, the autowiring is going to be the best option for dep injection. 

I'm assuming something like this should work using the DI container, which Sage just extends— 
https://gist.github.com/davejamesmiller/bd857d9b0ac895df7604dd2e63b23afe#basic-usage

**Comment by darrenjacoby** [comment]
Cool, got it working using the Sage container. 

So you could do this; 

**app/Dep/ClassA.php**

```php
<?php

namespace App\Dep;

class ClassA
{
    private $classB;

    public function __construct(ClassB $classB)
    {
        $this->classB = $classB;
    }

    public function get()
    {
        return 'Class A and ' . $this->classB->get();
    }
}
```

**app/Controllers/Single.php**
```php
<?php

namespace App\Data;

use Sober\Controller\Controller;

use App\Dep\ClassA;

class Single extends Controller
{
    private $classA;

    public function __construct(ClassA $classA)
    {
        $this->classA = $classA;
    }

    public function getClassA()
    {
        return $this->classA->get();
    }
}
```

I'll push to dev-master soon for further testing.

**Comment by mtx-z** [comment]
Is the 

    public function __construct(ClassA $classA)
    {
        $this->classA = $classA;
    }

From Single Controller only ran once ? Or multiple times ? As i remember trying to use the __construct to put some add_filters, and it wasn't good cause it was ran multiple times: and so filter added multiple times.

**Comment by darrenjacoby** [comment]
@mtx-z yeah seems to be only running once.
