### ISSUE TITLE
Cannot import controller classes after last update

### ISSUE THREAD

**Issue by asretux** [soberwp/controller#51]
After the last update on master, while using the Sage9 WordPress Theme, the App class is not loaded properly.

After reverting our composer.json wpsober/controller depedency to tag 9.0.0-beta.4, this proble does not occur.

**Comment by Log1x** [comment]
Looks to be a namespace issue.

![Screenshot](https://log1x.com/screenshots/2017-09-17_20-59-59_8hP01.png)

**Comment by darrenjacoby** [comment]
Are you using PSR4? 

You need to use the correct namespacing. This would have to change on Sage demo controller files too. 

```
<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class About extends Controller
{

}
```

**Comment by asretux** [comment]
@darrenjacoby I see, PSR4 is the issue.

I'm opening an issue in the Sage9 beta 4 repo to, at least, bind the composer.json beta4 tag to the proper soberwp/controller tag, instead of dev-master.

**Comment by Log1x** [comment]
Hmm. I changed the namespaces on all of my controllers and dumped autoload from Composer and am still having the same error despite `App\Controllers\App` existing now.

Will look into it more to see if it's on my side, but it's the same complaint about line 19 of `controller.php`

**Comment by Log1x** [comment]
The only "fix" I've done is adding `"App\\Controllers\\": "app/controllers"` to my autoload and then in any non-view I want to use a controller function in I have to do `use App\Controllers` as well as escape any of my helpers I use in my Controllers to `\App\helper_name()`, etc.

**Comment by monkeymonk** [comment]
The controllers are not been included anymore from the Loader.
So, yes, a workaround is to setup `composer.json` to autoload `app/controllers` files directly.

**Comment by darrenjacoby** [comment]
Sorry everyone, I've been meaning to take a look at this, but just in the process of moving residences so time has been limited. I'll look into a solution as soon as I can.

**Comment by moonorongo** [comment]
In composer.json:
```
  "require": {
    ....
    "soberwp/controller": "9.0.0-beta.4"
  },
```
has a solution for me

**Comment by greatislander** [comment]
@moonorongo There are new changes in the master branch which is what this thread is about.

**Comment by moonorongo** [comment]
thanks!

**Comment by darrenjacoby** [comment]
@Log1x the App/Controllers namespace should be working out the box. I'll re-check my side, but I did not need to change composer.json to include.
