### ISSUE TITLE
Improvment Request for declaring variables

### ISSUE THREAD

**Issue by webstractions** [soberwp/controller#52]
T'would be nice if all data fell under one blanket function like `_data()` and you did all your variable declarations there.  Having to do individual (non-static) functions just to declare variables is tedious. It is also confusing when you start mixing them with static functions.

I would like to see something like this within a controller:

```php

public function _data() {
    
    $item = [
       // get some data from external class
    ];
    $title = $this->transform( get_the title() );
    $another_var = function() {
        // do some more stuff here
   }

  return compact( 'item', 'title', 'another_var');
}
```

Now you have a very clear, simple, and easier to read function for your variables. Using functions just to declare variables is counter-intuitive. A lot of people are getting hung up on this (I know I did).

**Comment by darrenjacoby** [comment]
The above approach could also become messy, if there's one place where all variables are assigned and then there are multiple functions within that. The idea behind functions even for variables was that something is returned, perhaps after some if/else statements.

You could also create a public function called data and return object notation, so you could access using `$data->title` in the view.

I could perhaps look at exposing public variables defined within the class for very basic variables.

```php
class Single extends Controller
{
    public $basic = 'basic';
}
```

I'm not sure it's the best approach though, as then internal Controller reserved variables may need to be changed to `$__active = true` or something along those lines to avoid conflicts. Although I suppose that could also happen with a public static function.

**Comment by webstractions** [comment]
@darrenjacoby Yep, don't sweat it.

**Comment by darrenjacoby** [comment]
Cool, going to leave for now to avoid adding any additional complexity/confusion, but will review if there are more requests for something like this.
