### ISSUE TITLE
Default directory

### ISSUE THREAD

**Issue by dmgawel** [soberwp/controller#54]
Hi,

Sometimes there is a point in moving required theme files (`functions.php`, `style.css`, `index.php`, `screenshot.png`) to theme's top-level directory. This might even become an option in Sage: https://github.com/roots/sage-installer/issues/3. When those files are moved, `get_template_directory()` points to root folder and it breaks default directory both for Controller and Models:
https://github.com/soberwp/controller/blob/93aa3ccd869b6092eefb941e342382ce7e3b00db/src/Loader.php#L32

My proposition is to use `get_theme_file_path()` without `dirname()` instead. Thanks to Sage filter (https://github.com/roots/sage/blob/b4421be2696bd6021a11eb6893bb6fbb8a949d15/resources/functions.php#L80) it points to root directory when using default Sage setup, and when `functions.php` are moved this filter must be disabled anyway, so it also points to root directory. Thanks to that this is a non-breaking change.

WDYT?

**Comment by darrenjacoby** [comment]
Thanks @dmgawel, good to note the possible change. I may be changing this filter to a namespace filter (dev-master uses PSR4 loading), and from there I can determine the path. I'll be sure to implement the above solution when determining that path.
