### ISSUE TITLE
Implementing Tree only works for the direct parent

### ISSUE THREAD

**Issue by Sharsie** [soberwp/controller#60]
I promise this is the last issue I am creating today :)

While trying to solve the hierarchy problem with #59 I have encountered an issue when implementing a `Tree` from `SingePost` controller while also having `Single` and `Singular` controllers present

Maybe this is the correct behaviour, but it wasn't clear from the readme, so I just want to make sure

The most specific controller always inherits the data from its direct parent **only**

**Expected behaviour:**
When `SinglePost` controller implements `Tree` I would expect it to inherit data from `Single` and `Singular`

**Actual behaviour:**
Only data from `Single` are inherited while data from `Singular` are dropped

**How to reproduce:**
Given this pattern:
```
class Singular {
    public function item()
    {
          return 'singular:item';
    }
}
```
```
class Single {
    public function other_item()
    {
         return 'single:other_item';
    }
}
```
```
class SinglePost implements Tree {

}
```

When calling `{{ $other_item }}` in a blade template, it correctly prints out 'single:other_item';
When calling `{{ $item }}` it throws an error 

Now the solution ofcourse would be for `Single` to also implement `Tree` and then everything is inherited down

But is this the expected behaviour of the hierarchy? If it is, we should ammend the documentation to explain the behaviour a bit better.

If it is not then I think we would have to tackle the data inheritance in a different way

**Comment by darrenjacoby** [comment]
That should be the expected behaviour, I'll take a look at this.

**Comment by darrenjacoby** [comment]
Thanks for picking this up this bug. I have a fix, just need to clean it up.
