### ISSUE TITLE
Anyway to assign a controller manually to a partial?

### ISSUE THREAD

**Issue by Pushplaybang** [soberwp/controller#61]
I'm really enjoying using controllers in WP and combined with sage 9, this has totally brought WP development into a whole new paradigm that's actually enjoyable again.

I'm wondering if there is any way to manually assign a  controller to a template, that is not within the hierarchy.  While traits certainly help with modularity, it would be great to be able to create a controller and manually bind it to a view partial.

**Comment by darrenjacoby** [comment]
Hey Paul, you can define a template with the dev-master version, set for release as soon as Sage 9 goes stable. You could use parameter `$template = 'name-of-template';` within the Controller file. This however won't work for a partial. The data is sent through on a per template basis, so targeting only partials wouldn't be possible.

**Comment by Pushplaybang** [comment]
@darrenjacoby do you mean that this would be applicable only to templates that fall within the usual WP hierarchy?

**Comment by darrenjacoby** [comment]
Yea, the override would only apply to templates that fall within the WP hierarchy. It's useful for templates that use underscores instead of hyphens.

**Comment by Pushplaybang** [comment]
okay cool, any plan to support applying controllers to specific templates /  disabling the hierarchy for that controller?  or is that outside the scope?

**Comment by darrenjacoby** [comment]
Yea, so just to clarify. 

Using dev-master, you could specify the template using `$template = NAME_OF_TEMPLATE`; in the Controller.  As long as the Controller class isn't named as per the hierarchy, it will be disabled from the hierarchy, but could be included using the template override above.

**Comment by Pushplaybang** [comment]
awesome.  So it is totally possible then.  thanks.
