### ISSUE TITLE
Cannot redeclare register_extended_post_type()

### ISSUE THREAD

**Issue by webberwang** [soberwp/controller#62]
` Fatal error: Cannot redeclare register_extended_post_type() (previously declared in /srv/www/codelab.com/current/vendor/johnbillion/extended-cpts/functions.php:59) in /srv/www/codelab.com/current/vendor/soberwp/models/dist/johnbillion/extended-cpts/functions.php on line 69`

**Comment by darrenjacoby** [comment]
This is a Models issue which was fixed a few days ago
