### ISSUE TITLE
Problem with loading data on custom post type templates in 2.0.0

### ISSUE THREAD

**Issue by slackday** [soberwp/controller#63]
Hi

Just tried out v2.0.0 and ran into an issue with data not loading on some templates.

I tracked the issue down to custom post type naming and I'm not sure how to fix this the best way.

For example I have `cpt_calendar` post type. WordPress use template page `archive-cpt_calendar` for the archive page on this post type.

After updating I renamed the controller to ArchiveCptCalendar since filename should now be same as the class name for autoloading.

All class names goes through this function

```
    public static function convertToKebabCase($str)
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]/', '-$0', $str));
    }
```

to determine the template to load data for so the controller looks for `archive-cpt-calendar` not `archive-cpt_calendar`.

I can get it to work by overwriting `$template` in Controller with `protected $template = 'archive-cpt_calendar';`

This is OK in my case but I would suggest putting an instruction that custom post types should be named a specific way.

Or if someone else has a cleaver way so others don't run into this issue :)

**Comment by darrenjacoby** [comment]
Yeah, the way you're dealing with it is the correct way. Underscores are an issue, so using the template override is the best way to handle them.
