### ISSUE TITLE
Trouble Upgrading from 9.0.0-beta4

### ISSUE THREAD

**Issue by rorymcdaniel** [soberwp/controller#66]
After upgrading to 2.0.0 from 9.0.0-beta4, I can only get static methods to work in the templates. I am using the Sage 1.0 release.

I change app/controllers to app/Controllers, changed the namespace of the two example controllers to `App\Controllers` and changed the filenames to `App.php` and `FrontPage.php`

Again, using the default examples from Sage, in resources/views/partials/page-header.blade.php, I have to change `App::title()` to `\App\Controllers\App::title()` - This static function works as expected.

However, any public methods do not appear to show up in the templates.

When I put `@debug` into resources/views/app.blade.php I get:
`Warning: reset() expects parameter 1 to be array, null given in /home/vagrant/Code/alairhomes3.0/wp-content/themes/alairhomes/vendor/soberwp/controller/src/Debugger.php on line 34`
There is the same error repeated for lines 37 and 71

Is there something I'm doing wrong or something I missed when upgrading?

**Comment by darrenjacoby** [comment]
It sounds like there's no data being passed in, is there any chance you can set up a repo for me to take a look at?

**Comment by rorymcdaniel** [comment]
I'll see what I can do there, but I have some more information for you. I was looking at
`vendor/soberwp/controller/src/Loader.php` specifically `protected function setPath()`

If I change the name of the folder to `app/controllers` and then add the following to the PSR4 section of composer.json, everything works:
` "App\\Controllers\\":"app/controllers/"`

It looks like setPath() is looking for files in app/controllers, and not returning anything because it's actually app/Controllers.

**Comment by rorymcdaniel** [comment]
Just sent invite to a private repo

**Comment by darrenjacoby** [comment]
package.json still shows `"soberwp/controller": "9.0.0-beta4"`

Did you revert for the time being?

**Comment by rorymcdaniel** [comment]
That was a different branch. I just granted you access on bitbucket as a private repo instead of github. Look at branch soberwp/controller

**Comment by rorymcdaniel** [comment]
I don't know if this makes any difference, but this is a subfolder multisite. I'm using Laravel Homestead for my dev environment.

**Comment by mcaskill** [comment]
> It looks like setPath() is looking for files in app/controllers, and not returning anything because it's actually app/Controllers.

I had the same issue when it came to deploying a project to a _case-sensitive_ staging server (I was from a case-insensitive local environment).

The simplest solution I think of would be to add a filter to `Loader::setPath()` similar to `Loader::setNamespace()`.

```php
protected function setNamespace()
{
	$namespace = 'App\Controllers';
	if (has_filter('sober/controller/namespace')) {
		$namespace = apply_filters('sober/controller/namespace', $namespace);
	}

	$this->namespace = $namespace;
}

protected function setPath()
{
	$path = get_theme_file_path() . '/' . strtolower(str_replace('\\', '/', $this->namespace));

	if (has_filter('sober/controller/path')) {
		$path = apply_filters('sober/controller/path', $path);
	}

	$this->path = $path;
}
```

**Comment by darrenjacoby** [comment]
OK, I see the issue. 

```
protected function setPath()
{
    $this->path = get_theme_file_path() . '/' . strtolower(str_replace('\\', '/', $this->namespace));
}
```

`strtolower` needs to be removed. I'll do a release tomorrow to fix this.

**Comment by mcaskill** [comment]
> strtolower needs to be removed.

If removed, we will need to make sure `App` is also capitalized in our theme's directory tree.

**Comment by darrenjacoby** [comment]
That's true, but I'll still fix it tomorrow by taking another route, haha

**Comment by darrenjacoby** [comment]
Thanks to @rorymcdaniel PR this is resolved. I'll tag a release as soon as all new issues are sorted.

**Comment by slamorte** [comment]
I have the same issue. Following up on this and I'm running the most recent code. 

To clarify, does `app/Controllers/app.php` need to be renamed `App/Controllers/App.php`? And if so the documentation needs to be changed.

**Comment by rorymcdaniel** [comment]
In order to be PSR4 compliant, `\App\Controllers\App::class` needs to be app/Controllers/App.php.
