### ISSUE TITLE
ACF Pro Support

### ISSUE THREAD

**Issue by rorymcdaniel** [soberwp/controller#67]
This is more of a feature request than anything else. I use ACF Pro for custom fields. I set up an override locally to extend your package and let it also include the fields on the site-wide options page. Is this a feature you're willing to include?

I'd be happy to do a pull request with the feature, but I wanted to see if you were interested and if you had any thoughts on how you would want to integrate it.

**Comment by darrenjacoby** [comment]
I would yes. Could add it to the App class?

**Comment by rorymcdaniel** [comment]
@darrenjacoby I was hoping you could give me a little feedback on #72 and see if you'd like to move forward with this feature.

**Comment by darrenjacoby** [comment]
Hey @rorymcdaniel 

Def keen to include the options to the App Class, but would prefer to not have a param $acfPro just for the options field. I'm going to code this so that it happens automatically. The App Class is inherited by all templates, so tree isn't required using this approach. I'm going to do some work on Controller tonight so will take a look at implementation.

**Comment by rorymcdaniel** [comment]
That makes perfect sense, and is ironic because that's how I'd done it for my own implementation first and just assumed you'd want the ability to turn it off/on. Take a look at #73 and see if that's more to your liking.

**Comment by darrenjacoby** [comment]
Thanks for the PR. The code on Acf.php runs for each page, it only needs to be run on App.php and not each page. I'll amend and include in the next 2.0.2 release.

```
if(function_exists('acf_add_options_page')){
            $options = Acf::convert(get_fields('options'));
            $data = (object) array_merge((array)$data, (array) $options);
}
```

**Comment by pawelkleczek** [comment]
Two thumbs up for this feature 👍 👍

**Comment by darrenjacoby** [comment]
Coming in 2.0.2. Closing for now.

**Comment by christianmagill** [comment]
@darrenjacoby, I'm not sure merging the options with the rest of the data is the right move. Maybe keep them in a separate $options array. If they are being merged however, I think the order in the array_merge should be swapped, so that the data for the current view overwrites the options instead of the other way around, as it is now. That way you might have a global option on the options page, that can be overwritten at a page level. Thoughts?

**Comment by thomascharbit** [comment]
Hi,

On 2.0.2 you are replacing all ACF data with data from the option page instead of merging them?
Cannot access current page ACF fields with 2.0.2..

**Comment by darrenjacoby** [comment]
@thomascharbit are the fields named the same?

**Comment by thomascharbit** [comment]
Hi @darrenjacoby thanks for helping 😃 

Actually i have no options page, so no fields!
I just started a new project today, added some ACF fields on a CPT and added `$acf = true` to its controller.
A `@debug` in my view file show no ACF data.
If i comment out the part where the ACF module gets the options fields, it works.
If i downgrade to 2.0.1 it works too..

**Comment by ecruhling** [comment]
I have the same problem as well; project was using 2.0.1 - I updated to 2.0.2 this morning and no ACF fields are being returned. I have no options page.
Rolling back to 2.0.1 and it works as expected.

**Comment by darrenjacoby** [comment]
Haha, shit. Let me take a look.

**Comment by darrenjacoby** [comment]
Just re-released 2.0.2, try clear your cache and re-update, should work now.

**Comment by thomascharbit** [comment]
Works for me, i have a PHP warning though:

`Warning: array_merge(): Argument #1 is not an array in /home/vagrant/(...)/vendor/soberwp/controller/src/Module/Acf.php on line 96`

**Comment by darrenjacoby** [comment]
Ah sorry, working fast here, I'll fix that in a bit.

**Comment by christianmagill** [comment]
I have the same warning and option fields do not make it to the template.

**Comment by darrenjacoby** [comment]
@christianmagill it works from App. Are you using $acf = true on App.php?

**Comment by christianmagill** [comment]
Yes, I am using $acf = true in App.php

**Comment by illycz** [comment]
I'm using 2.1.0 version and `"protected $acf = true;"` in App.php. And I don't get the options fields in blade template. Is there something I need to know?

Thanks
