### ISSUE TITLE
Base controller issues

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#7]
The base controller doesn't work without another matching controller for the template being loaded.

If I just have a base.php controller then the variables are not available to the page.blade.php template or even the base.blade.php template. However, if I create a page.php controller with a dummy function, the base controller variables become available.

Other than that things seem to be working great!

**Comment by darrenjacoby** [comment]
Thanks for flagging this! 

I didn't consider that scenario but it's def a valid one. 

It's a quick fix so will upload a new ver soon.

**Comment by darrenjacoby** [comment]
Just committed 1.0.0-beta1.1 which will fix.

**Comment by christianmagill** [comment]
Thanks
