### ISSUE TITLE
Release the newest version

### ISSUE THREAD

**Issue by mrtnsn** [soberwp/controller#74]
Could you make a tag for fdc4692, this fixed a couple of issues for us and would love to not be depended on `dev-master`

**Comment by darrenjacoby** [comment]
@mrtnsn sure, I will tag a release this weekend.

**Comment by mrtnsn** [comment]
@darrenjacoby cheers 👍

**Comment by mrtnsn** [comment]
@darrenjacoby status on this?

**Comment by darrenjacoby** [comment]
Just released 2.0.1
