### ISSUE TITLE
Fatal error: Uncaught ReflectionException on my staging server

### ISSUE THREAD

**Issue by thelar** [soberwp/controller#75]
Hi,

I posted an issue I was having with a site I'm developing which I ran into when deploying it to my staging server [here](https://discourse.roots.io/t/fatal-uncaught-reflectionexception-error-with-controller-2-0-0/11859). I've had to bite the bullet and revert back to the 9.0.0-beta.4 version of controller to get around this. But I thought I'd post here because I have now tried setting up a completely fresh install of bedrock/sage with no development work, all I've done is change controller to version 2, run `composer update` and install ACF Pro. I renamed app.php to App.php and changed it's namespace to App\Controllers. However I still get this error on my staging server:
```
[09-Mar-2018 12:33:48 UTC] PHP Fatal error:  Uncaught ReflectionException: Class App\Controllers\App does not exist in /home/chapterserver1/dev/test/web/app/themes/bbc/vendor/soberwp/controller/src/Loader.php:119
Stack trace:
#0 /home/chapterserver1/dev/test/web/app/themes/bbc/vendor/soberwp/controller/src/Loader.php(119): ReflectionClass->__construct('App\\Controllers...')
#1 /home/chapterserver1/dev/test/web/app/themes/bbc/vendor/soberwp/controller/src/Loader.php(49): Sober\Controller\Loader->setClassesAlias()
#2 /home/chapterserver1/dev/test/web/app/themes/bbc/vendor/soberwp/controller/controller.php(22): Sober\Controller\Loader->__construct(Object(Brain\Hierarchy\Hierarchy))
#3 /home/chapterserver1/dev/test/web/wp/wp-includes/class-wp-hook.php(286): Sober\Controller\loader('')
#4 /home/chapterserver1/dev/test/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/chapterserver1/dev/test/web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /home/chapterserver1/dev/test/web/wp/wp-settings.php(450): do_actio in /home/chapterserver1/dev/test/web/app/themes/bbc/vendor/soberwp/controller/src/Loader.php on line 119
```
It runs fine when I change Controller back to the old version and `composer update`

This exactly mirrors the error I was getting previously, however I don't get this on my local dev site.

You can see my phpinfo [here](http://www.chapterserver1.co.uk/phpinfo.php)

I have also tried the solution posted in [this commit](https://github.com/hambos22/sage-woo/commit/84aad57c3c2c6be7e8aaae8fbf2e9b4f32fa03cb) but with no luck.
Hope someone can help with this as I would like to be able to access my ACF fields in a slicker way.

Many thanks
Kevin

**Comment by darrenjacoby** [comment]
I think this is an issue with 2.0.0, there was an issue with caps/lowercase. Could you try dev-master and see if it still happens? I'll be tagging 2.0.1 in the next day or two.

**Comment by thelar** [comment]
Hi Darren,
Sorry for delay, I just got around to trying this but no luck I'm afraid, still getting the same errors with `dev-master`

Kevin

**Comment by darrenjacoby** [comment]
Please update to 2.0.1 and make sure that classes are namespaced correctly.

**Comment by kuiperr005** [comment]
Hi, I am having this same issue on our server, with version 2.0.1 and class namespaces setup correctly. Locally it works, but not on the server itself. I'm getting the following error:

`Fatal error: Uncaught ReflectionException: Class App\Controllers\App does not exist in /home/public/sites/www.pijlmanagement.nl/app/themes/mytheme/vendor/soberwp/controller/src/Loader.php:74 Stack trace: #0 /home/public/sites/www.site.nl/app/themes/mytheme/vendor/soberwp/controller/src/Loader.php(74): ReflectionClass->__construct('App\\Controllers...') #1 /home/public/sites/www.site.nl/app/themes/mytheme/vendor/soberwp/controller/src/Loader.php(35): Sober\Controller\Loader->setPath() #2 /home/public/sites/www.site.nl/app/themes/mytheme/vendor/soberwp/controller/controller.php(22): Sober\Controller\Loader->__construct(Object(Brain\Hierarchy\Hierarchy)) #3 /home/public/sites/www.site.nl/wp/wp-includes/class-wp-hook.php(286): Sober\Controller\loader('') #4 /home/public/sites/www.site.nl/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /home/public/sites/www.site.nl/wp/wp-includes/plugin.php(453): WP_Hook->do_a in /home/public/sites/www.site.nl/app/themes/mytheme/vendor/soberwp/controller/src/Loader.php on line 74`

**Comment by reiterbene** [comment]
same issue here.
on localhost everything works perfect - on the server side I get the same error.

**Comment by darrenjacoby** [comment]
You just need to rename app/controllers to app/Controllers as per the PSR4 spec...
