### ISSUE TITLE
Fatal error (server only) - after migrating from 9.0.0-beta.4 to 2.0.0

### ISSUE THREAD

**Issue by pawelkleczek** [soberwp/controller#77]
Hi guys,

after migrating to v2 i get this error on server. Locally it works perfectly well. Is it also a problem with case-sensitive environment? Is there gonna be some update soon?

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function have_posts() on null in /var/www/pola-dev/web/app/uploads/cache/a3af0dc36cf995ecb4c9cbab1d73c61a74904e85.php:10 Stack trace: #0 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/illuminate/view/Engines/PhpEngine.php(42): include() #1 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/pola-d...', Array) #2 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/var/www/pola-d...', Array) #3 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/illuminate/view/View.php(120): Illuminate\View\View->getContents() #4 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/illuminate/view/View.php(85): Illuminate\View\View->renderContents() #5 /var/www/pola-dev/web/app/themes/pola-custom-theme/vendor/roots/sage-lib/Template/B in /var/www/pola-dev/web/app/uploads/cache/a3af0dc36cf995ecb4c9cbab1d73c61a74904e85.php on line 10

**Comment by slamorte** [comment]
This happened to us.

Check your `app/` folder on the server and see if you have more than one `Controllers/` folder and if it's capitalized. Your repo and server might have two controllers folders with different case, while your OSX development environment will show only one folder. This issue might apply to any other file or folder where you've changed case on the OSX. 

We fixed it with:
```
git rm -r Controllers
git checkout controllers
git mv controllers temp
git mv temp Controllers
git checkout Controllers
```

This merged the two folders on OSX and the next commit resolved the  Uncaught Symfony error.

**Comment by pawelkleczek** [comment]
Well, actually you're 100% right, because i did have two controller folders, one capitalized, and one not. I think it was due to me removing folder, or changing capitalization with functions like mv or rm and not it's git equivalents. But i changed it on server (also stupidly choosing mv over git mv), and it still results in error being thrown.

![zrzut ekranu 2018-03-16 o 10 20 29 2](https://user-images.githubusercontent.com/20242777/37512920-b396e23a-2903-11e8-83f8-fb14a1a130ba.png)

And this is the controller that causes mistake. It looks like $logotypy is not being passed to the view.

![zrzut ekranu 2018-03-16 o 10 22 13 2](https://user-images.githubusercontent.com/20242777/37512991-ed71aac6-2903-11e8-8f45-170be8cf770d.png)

**Comment by pawelkleczek** [comment]
the last line from error message is (/var/www/pola-dev/web/app/uploads/cache/a3af0dc36cf995ecb4c9cbab1d73c61a74904e85.php on line 10)

this is the code:

![zrzut ekranu 2018-03-16 o 10 28 32 2](https://user-images.githubusercontent.com/20242777/37513238-d11dda6a-2904-11e8-97c8-532e7b9f4851.png)

**Comment by slamorte** [comment]
There's more to the solution. Here's what I posted over on the Sage forums:

Rename
`app/Controllers/app.php`
to
`app/controllers/App.php`

In composer.json replace line 31 with:
```
  "App\\": "app/",
  "App\\Controllers\\": "app/controllers/"
```
As per this link at soberwp.

Run
`composer dump-autoload`

Run (optional?)
`yarn build`

These steps seemed to have solved my empty ACF and namespaced variables issue. I have no idea why; namespacing is a black art to me.

Note 1: if you are working on a caps-insensitive system like OSX and pushing to a caps-sensitive server like linux you might have additional issues with duplicate filenames. Use the file explorer in Github or wherever you keep your repo to check for duplicate but case-changed versions of folders or files in app/ (i.e. `controllers` and `Controllers`, `single.php` and `Single.php`

Note 2: all controller names must be CamelCaps versions of the template names with dashes removed — `front-page.blade.php` becomes `FrontPage.php`

**Comment by darrenjacoby** [comment]
You guys could also use dev-master which will fix this. I'm going to create a new version shortly.

**Comment by pawelkleczek** [comment]
i have stupid question - how to change to dev-master? i see only one branch... :P

**Comment by slamorte** [comment]
If dev-master makes the controller folder case-insensitive that would be great.

At this point thought the bigger problem is fixing my "fixes" from trying to capitalize the folder in the first place. The duplicate folders keep giving me unresolvable git merge conflicts.

**Comment by pawelkleczek** [comment]
yeah, that was it!

"App\\Controllers\\": "app/controllers/"

thanks @slamorte

**Comment by darrenjacoby** [comment]
You can now upgrade to 2.0.1. 

This was fixed with merge https://github.com/soberwp/controller/pull/71 from @roryatbrightoak

**Comment by slamorte** [comment]
`composer update soberwp/controller` and it seems to be working fine!

**Comment by pawelkleczek** [comment]
for me too. And no longer need to add "App\Controllers\": "app/controllers/" to composer.json

thanks @darrenjacoby !!
