### ISSUE TITLE
Altering data array in controller

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#79]
With version 2.0.1 I can no longer alter the data through the constructor function.

The first hurdle is that the $data property has been changed back to private. However, even if I alter the $data array it just gets overwritten.

What I'm trying to do is the below...

```
public function __construct() {
        $options = get_fields('options');
        $fields = get_fields(get_queried_object());

        if ( is_array( $options ) ) {
            $this->data = array_merge( $options, $this->data );
        }

        if ( is_array( $fields ) ) {
            $this->data = array_merge( $fields, $this->data );
        }
    }
```

With this setup, acf post fields would overwrite acf option fields, and functions would overwrite both.

I'm not sure how I can replicate this in version 2.0.1. I'm running into an issue where I need to upgrade because of the controller methods were running multiple times on version 9 beta 4.

Thanks for any help you can provide.

**Comment by darrenjacoby** [comment]
2.0.2 releasing soon, just changed data back to protected.

**Comment by christianmagill** [comment]
@darrenjacoby, Any update on 2.0.2? Waiting on this and the filter to disable returning ACF arrays as objects. Thanks
