### ISSUE TITLE
App\sage not defined when deploying using Trellis

### ISSUE THREAD

**Issue by aaroneight** [soberwp/controller#8]
I'm deploying using Trellis, and since Controller is a mu-plugin, I'm guessing that it gets enabled before Sage is enabled and as such is throwing a fatal error during a trellis deploy process, thereby exiting the deploy. 

`PHP Fatal error:  Uncaught Error: Call to undefined function App\\sage() in /srv/www/viewfind.com/releases/20170228183833/web/app/mu-plugins/controller/controller.php:46`

Can we check that the namespace exists before calling the function?

**Comment by darrenjacoby** [comment]
Hey @aaroneight cool, I will take a look at this tomorrow. Just appears to the debugger calling the Blade directive.

**Comment by darrenjacoby** [comment]
@aaroneight just pushed 1.0.0beta1.2 with a check to see if the function is defined, let me know if that works.
