### ISSUE TITLE
"protected $acf = true" not returning ACF group fields

### ISSUE THREAD

**Issue by slamorte** [soberwp/controller#81]
I'm having an issue with `protected $acf = true;` not returning ACF fields as expected with soberwp v2.0.1. 

app/Controllers/App.php:
```
<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class App extends Controller
{
  protected $acf = true;

  public function siteName()
  {
    return get_bloginfo('name');
  }
[etc]
```

views/partials/template.blade.php:
```
{{  get_field('to4_disclaimer_selection', $article_id) }}
{{ $to4_disclaimer_selection }}
@dump( $to4_disclaimer_selection )
{{ site_name }}
```

Results:
```
Some Value Here

NULL
MySiteName
```

This seems to be true whether I echo the results in a partial, or in single.blade.php, or anywhere else. Public functions work, ACF variables are empty. 

Can you give me a pointer on how to start to troubleshoot this further?

**Comment by darrenjacoby** [comment]
Yes that's correct. It returns an object. Please feel free to add a PR for the README, else I'll get to that early next week.
