### ISSUE TITLE
2.0.2

### ISSUE THREAD

**Issue by christianmagill** [soberwp/controller#88]
@darrenjacoby 

Using the new 'sober/controller/acf/array' filter I get...

Notice: Undefined variable: rawFilter in ...vendor/soberwp/controller/src/Module/Acf.php on line 16

Notice: Undefined variable: rawFilter in ...vendor/soberwp/controller/src/Module/Acf.php on line 16

Notice: Undefined variable: rawFilter in ...vendor/soberwp/controller/src/Module/Acf.php on line 16

**Comment by ligne13** [comment]
I updated to 2.0.2 and I also have a bug with ACF fields : 

> Fatal Error : cannot use object of type StdClass as array...

**Comment by darrenjacoby** [comment]
Use 2.0.1 for now! 2.0.2 is not tagged!

**Comment by ligne13** [comment]
OK, but how `composer update` found the 2.0.2 version ? I have "~2.0.1" in my composer.json.

thanks !

**Comment by darrenjacoby** [comment]
I've reworked the ACF module, now placing `protected $acf = true;` in `App.php` automates all fields. It places the ACF options fields into a variable called `$acf_options`.

This means you no longer need to place `protected $acf = true;` in each Controller, or even create a Controller file for pages which just require ACF fields.

![image](https://user-images.githubusercontent.com/15921694/42707655-3f88542e-86db-11e8-89ac-332c5af60075.png)

**Comment by christianmagill** [comment]
@darrenjacoby Thanks! Any update on 2.0.2? Are this issue and and the array to object filter available in master?

Thanks

**Comment by darrenjacoby** [comment]
@christianmagill I updated dev-master over the weekend for testing. I'll tag it soon. 

https://twitter.com/withjacoby/status/1017839898454261760

**Comment by christianmagill** [comment]
@darrenjacoby Any update on when this will be tagged?

Thanks,

**Comment by darrenjacoby** [comment]
2.1.0 is tagged, which is the latest.

**Comment by christianmagill** [comment]
Oh thanks, decimal places elude me.
