### ISSUE TITLE
post loop?

### ISSUE THREAD

**Issue by jajouka79** [soberwp/controller#9]
great package, excellent addition for bedrock / sage. i have functions in src/single.php in which i am trying to output get_the_content() and post_class(), they are both empty, the_title is not empty. is this because its not inside of the loop?

**Comment by darrenjacoby** [comment]
@jajouka79 thanks, I've only just noticed that the $post object only get's passed on pages and not posts.

I'm going to update the Controller to include $post by default for posts, in the meanwhile, this will work within your controller; 

```php
public function content()
{
    return \get_post()->post_content;
}
```

**Comment by jajouka79** [comment]
great thanks
