### ISSUE TITLE
What's up with the version numbers?

### ISSUE THREAD

**Issue by Muffinman** [soberwp/controller#90]
I'm a bit confused why 2.0.1 is a newer release than 9.0.0-beta.4? What's up with the version numbers?

I notice that [roots/sage](https://github.com/roots/sage) is using 9.0.0-beta.4, is there anything special about these versions? Is it safe to switch to 2.0.1 and benefit from the extra features?

**Comment by darrenjacoby** [comment]
When it was first released as a Composer package, I followed the Sage 9 versioning. Since then I've broken away from that and hence 2.0.0. It's safe, and recommended, to switch to 2.0.1.
