### ISSUE TITLE
Controller support for child themes breaks in >2.0.0

### ISSUE THREAD

**Issue by craigpearson** [soberwp/controller#91]
Roots supports child themes, and supports the overriding of all core app data and resources. Since sober/controller >= 2.0.0 behaviour of the controller breaks child themes with fatal errors

Previous to v 2.0.0 controllers were automatically inherited in child themes whether the controller file existed or not. Now a fatal error is thrown if the controller file present in parent is not also present in the child.

This means that controller methods cannot be inherited and must be duplicated within the parent and child themes for blade view inheritance to work as expected.

Controller v ~9.0.0-beta.4 works , where a controller present in the parent does not throw a fatal error if it doesn't exist in the child theme. You can also overwrite controllers in child themes because of this behaviour

**Comment by darrenjacoby** [comment]
I'm assuming PSR4 autoloading is the cause of this. I wonder what the correct way to handle such situations is. PSR4 is def the better way to handle getting the Controller files vs scanning a folder and requiring the files. Let me do some research and see, open to suggestions on this.

**Comment by craigpearson** [comment]
Yep PSR-4 is the reason behind it, I thought about tapping into traits to get around this issue of duplication as a middle ground. But after some deliberation I reached the conclusion that it'd be better to do something at autoload level, as a child theme should inherit by default and selectively override in it's nature

Let me know if there's anything specifically I can look into to assist / test

PS Great work on the controller so far 👍

**Comment by alfacommunication-alessandro** [comment]
Any good strategy to inherit Controllers from parent theme?
