### ISSUE TITLE
Controller for custom post templates wont load

### ISSUE THREAD

**Issue by mattrn** [soberwp/controller#92]
I am trying to create a controler for a custom post template with Sage 9.0.1 and 9.0.0-beta.4
This is my post template view(template-special.blade.php):
```blade
{{--
  Template Name: Special Blog Post
  Template Post Type: post
--}}

@extends('layouts.app')

@section('content')

<h1>{{ "content: ".$content }}</h1>

@endsection
```

This is my controller (template-special.php):

```php
<?php

namespace App;

use Sober\Controller\Controller;

class TemplateSpecial extends Controller
{

	public function content() {

		return "hi im content renderer";
		
	}
}
```

With this setup, no data gets passed to to the view.

@debug('hierarchy') in the view returns:

    controllers/app.php
    controllers/index.php
    controllers/singular.php
    controllers/single.php
    controllers/single-post.php
    controllers/single-post-test-post.php

If I remove the line `Template Post Type: post` and apply the template to a page instead of a post, it works and @debug('hierarchy') returns:

    controllers/app.php
    controllers/index.php
    controllers/singular.php
    controllers/page.php
    controllers/page-6842.php
    controllers/page-test-page.php
    controllers/template-special.php

It seems like some -data classes in the body are missing for posts.

**Comment by darrenjacoby** [comment]
I would recommend upgrading to 2.0.1 to begin with, then let me know if the issue continues.

**Comment by mattrn** [comment]
Hello darren, thanks for the fast response!
I upgraded to 2.0.1 and had to change the namespace for my controllers to `App\Controllers` and change the filenames to camelcase to get the site working again.

So my controller is now called TemplateSpecial.php
and my view is called template-special.blade.php.

The data is still not getting passed to the view but the debugger output changed:

App

    Data
        postobject
        site_namestringline 9—12
        social_settingsarrayline 34—48
        templatestringline 50—52
    Methods
        title14—32

Index

    Data
        get_head_stylestringline 15—17
        get_current_urlstringline 19—22
        get_redirect_urlstringline 24—31
    Methods
        getFallbackTiles33—60

SinglePostextends tree

    Data
        bread_crumbsstringline 16—19
        post_dataarrayline 21—37
        author_dataarrayline 39—49
        tagsbooleanline 51—55
        get_gridobjectline 58—96

**Comment by darrenjacoby** [comment]
Can you show me the body classes for template-special?

**Comment by mattrn** [comment]
when I use the template for a post:
```
post-template post-template-views post-template-template-special post-template-viewstemplate-special single single-post postid-6826 single-format-standard logged-in test-post app-data index-data singular-data single-data single-post-data single-post-test-post-data
```
when I use the template for a page:
```
page-template page-template-template-special template-special page page-id-6842 logged-in test-page app-data index-data singular-data page-data page-6842-data page-test-page-data template-special-data
```

**Comment by darrenjacoby** [comment]
This is there, so it should be passing the data `template-special-data`

I'll need to see the actual code to help further, but I don't think it's a Controller issue.

**Comment by Log1x** [comment]
`template-special-data` isn't showing up in his CPT, which is what he's having issues with. Same issue as #86.

You can find a solution [here](https://github.com/Brain-WP/Hierarchy/issues/14) until the dev branch of Brain-WP/Hierarchy is pushed to master along with [this](https://github.com/Brain-WP/Hierarchy/commit/bcdd745529a43fc68ae774ba9f68155e5742b95b) assuming it is functioning as intended.

**Comment by darrenjacoby** [comment]
Ah right, thanks @Log1x 

Yeah, waiting on the Brain-WP/Hierarchy release which should hopefully resolve this.

**Comment by mattrn** [comment]
Thanks for the help.
The Brain-WP/Hierarchy might be the root of my issue, although I am not trying to get the controller working for a custom post type, but for `post type = post`.
Is this the same thing? I'm not sure on the terminology here.

**Comment by darrenjacoby** [comment]
So, for the default post type? Then it should work.

**Comment by mattrn** [comment]
Yes the default post type and I need a controller for all `post type = post` posts that use a certaint blade template.
It works if I apply the template to 'post type = page' posts.
Sadly I cannot share the whole codebase, are there any files in particular you would like to see?

**Comment by darrenjacoby** [comment]
@mattrn I would need to see your App/Controller and resources/views/ folders to try recreate

**Comment by darrenjacoby** [comment]
@mattrn any updates here?

**Comment by mattrn** [comment]
I have now created a whole new Sage project and could reproduce the issue.
This is what I did:
- Set up a standard Wordpress installation
- Created a Sage project via composer
- Upgraded soberwp/controller to 2.0.1
- Added a controller and blade template for a page template
- Added a controller and blade template for a post template

Outcome:
-The controller for the page template works as expected, output of the blade template: 

> $content: This is TemplateCustomPage Controller

-The controller for the post template does not work, output of the blade template: 

> $content: 

This is the repository: https://github.com/mattrn/sage-test/

**Comment by darrenjacoby** [comment]
@mattrn thank you, I'll check this out now

**Comment by darrenjacoby** [comment]
Cool, confirmed, this was added to WP 4.7.  

This needs to come from one of the deps though, it's been coded but not yet tagged. I have asked for an eta. See here https://github.com/Brain-WP/Hierarchy/issues/15

Once this is tagged, it will work for Controller.

I noticed on your repo though that you're using folder name `controller/`. It should be `Controller/` to comply with PSR-4.

**Comment by mattrn** [comment]
Alright, thanks for the help!

**Comment by darrenjacoby** [comment]
In the meanwhile, here's another workaround. 

You could use a body_class filter to add a `-data` class to a specific post template. For example, in app/filters.php;

```php
add_filter('body_class', function ($classes) {
    // some logic
    if (is_page()) {
        $classes = array_merge($classes, ['custom-post-template-name-data']);
    }

    return $classes;
}, 20);
```

Then you could create a Controller called `CustomPostTemplateName.php` and it will work. Controllers are just run on body classes, so there is flexibility around customising them.

**Comment by mattrn** [comment]
Hello Darren,
thanks for the tip! I have implemented it like this and its working:
```
add_filter('body_class', function ($classes) {
    if (get_page_template_slug() === 'views/template-custom-post.blade.php') {
        $classes = array_merge($classes, ['template-custom-post-data']);
    }

    return $classes;
}, 20);
```
I guess I will continue with this workaround and upgrade as soon as the new version is available.

**Comment by darrenjacoby** [comment]
@mattrn good to hear. 

I'm going to tag a new release of Controller this week (2.1.0), and then will pull in the dev-master version of WP_Hierarchy on the Controller dev-master so that we can begin testing the post templates implementation.

**Comment by shaneparsons** [comment]
@darrenjacoby Any ETA on when 2.1.0 is going to be released?

**Comment by darrenjacoby** [comment]
@shaneparsons Likely this coming Sunday.

**Comment by darrenjacoby** [comment]
dev-master has 2.4 for Brain Hierarchy which should resolve this.
