### ISSUE TITLE
Handle form (POST/GET) requests

### ISSUE THREAD

**Issue by strarsis** [soberwp/controller#93]
@darrenjacoby: Are there examples for using the controller also for handling form POST/GET requests?

Somehow related: https://github.com/soberwp/controller/issues/78

**Comment by darrenjacoby** [comment]
@strarsis not at the moment

**Comment by strarsis** [comment]
@darrenjacoby: So as alternative I would have to use native PHP `$_POST`?

**Comment by darrenjacoby** [comment]
@strarsis yep
