### ISSUE TITLE
Unable to pass all fields from ACF to the view

### ISSUE THREAD

**Issue by storybynumbers** [soberwp/controller#94]
Hi folks,

I noticed that my ACF fields disappeared once I setup a custom Controller for my template. According to the docs, these can be automatically passed by setting the $acf property to true. That isn't working for me.

My controller:

```php
namespace App\Controllers;

use WP_Query;
use Sober\Controller\Controller;

class TemplateBlog extends Controller {

	// This does not work
	protected $acf = true;

	// This works
	public function header() {
		return array(
			'cta' => get_field('header_cta'),
			'image' => get_field('header_image'),
			'subtext' => get_field('header_text'),
			'subtitle' => get_field('header_subtitle'),
			'header_svg' => get_field('header_svg')
		);
	}

	public function blogs() {
		$blogs = new WP_Query('cat=2');
		return $blogs;
	}
}
```

And if I inspect from the template:

```blade
{{--
  Template Name: Blog
--}}
@debug
```

The output is missing my ACF fields (header_cta, header_image, etc):

```
Controller Debugger:
$site_name » string
$post » object
$header » array[5]
$blogs » object
```

I can access the data through the header() method I made, which returns an array of get_field() results, but that seems error prone to me.

Am I missing something with the ACF stuff? I'm new to Sage and Sober. Usually more of an Ignorant and Drunk guy really, so the chances that I'm doing something stupid are rather high. A tip would be highly valued! 

I'm using ACF Pro v5.7.2, and my theme is based off Sage v9.0.1. Sage provided me with 9.0.0-beta.4 of Sober.

**Comment by darrenjacoby** [comment]
Hey @storybynumbers 

You need to get the latest version. I would recommend dev-master for the next few days (as that includes passing in acf option page values automatically). I will be tagging 2.1.0 this week, which will include those changes. Let me know if that solves it for you.

**Comment by storybynumbers** [comment]
Hey Darren, great to hear from you!

I tried running off dev-master, but came across errors:

```
Fatal error: Uncaught ReflectionException: Class App\Controllers\App does not exist in /Users/yergeau/projects/saida/wp-content/themes/eval/vendor/soberwp/controller/src/Loader.php on line 75
```

Shall I check back later after 2.1.0 is tagged?

**Comment by darrenjacoby** [comment]
@storybynumbers you need to upgrade to PSR4 loading. 

Here's the changes to be applied; 
https://github.com/roots/sage/pull/2025/files

**Comment by darrenjacoby** [comment]
I've gone ahead and added this to the README file.

**Comment by storybynumbers** [comment]
That worked for me, @darrenjacoby. Thanks!

For anyone else with the same problem: take note of Darren's [instructions in the README](https://github.com/soberwp/controller/commit/9aac796d7fa8bc1d8697c76f9c16d47a92a45d79). The `controllers/` folder must be renamed to `Controllers/`, and class filenames need to have camelcase.

So in my case, `controllers/template_blog.php` became `Controllers/TemplateBlog.php`.

**Comment by darrenjacoby** [comment]
No problem! Closing.

**Comment by darrenjacoby** [comment]
Also I'm visiting Amsterdam in the next month or two (and possibly moving there next year), as a drunk guy too, bar suggestions welcome.
