### ISSUE TITLE
[Question] Moving composer.json

### ISSUE THREAD

**Issue by OwenMelbz** [soberwp/controller#96]
Hi - love the idea of this package, however having some problems customising something.

We want to use our root `composer.json` to handle the dependencies rather than one inside a theme folder.

When I add it to our main one via `composer require soberwp/controller` it installs fine.

We then update the autoload paths in the root composer to

```
"autoload": {
        "psr-4": {
            "App\\": "web/app/themes/theme-name/app/"
        }
    }
```

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in ............`

---

Any ideas how to get around this?

Thanks

**Comment by darrenjacoby** [comment]
@mcaskill nice solution
