### ISSUE TITLE
Class 'Illuminate\Support\Debug\Dumper' not found

### ISSUE THREAD

**Issue by codepuncher** [soberwp/controller#98]
With [Illuminate\Support](https://github.com/illuminate/support) being updated to 5.7.x, we lose the Debug namespace and classes. Looks like they've replaced it with Symfony Dump Server https://laravel.com/docs/5.7/releases.

Take this as a note for those that come across this issue until it is resolved.

**Comment by darrenjacoby** [comment]
@codepuncher thanks for the heads up. I will take a look at changing.

**Comment by Log1x** [comment]
```
composer require symfony/var-dumper --dev
```

**Comment by darrenjacoby** [comment]
Thanks @Log1x
